const unpublished = [
    {
        product_code: 67677,
        wondersoft_code: 23453,
        product_name: 'FDSON MP D3 TAB 1X10',
        manufacturer: 'WELLNESS REMEDIES PVT LTD',
        combination: '	LEVOCETIRIZINE 10 MG',
        status: 'Published',
    },
    {
        product_code: 34562,
        wondersoft_code: 78783,
        product_name: '	1 AL MAX TAB 1X10',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'LEVOCETIRIZINE 5 MG+MONTELUKAST 10 MG',
        status: 'Published',
    },
    {
        product_code: 98989,
        wondersoft_code: 34783,
        product_name: '	1 AL SYP 30ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'LEVOCETIRIZINE 2.5 MG /5ML',
        status: 'Published',
    },
    {
        product_code: 98687,
        wondersoft_code: 34573,
        product_name: '	1 AL TAB 1X10',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'LEVOCETIRIZINE 5 MG',
        status: 'Unpublished',
    },
    {
        product_code: 67487,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Published',
    },
    {
        product_code: 67487,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Unpublished',
    },
    {
        product_code: 67487,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Published',
    },
    {
        product_code: 67487,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Unpublished',
    },
    {
        product_code: 67487,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Published',
    },
    {
        product_code: 67487,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Published',
    }
];

const locationmaster = [
    {
        product_code: 67677,
        wondersoft_code: 23453,
        product_name: 'FDSON MP D3 TAB 1X10',
        warehouse_code: 'HO(1)',
        section: 'A (FWD)',
        lane: 2,
        rack: 'P',
        shelf: 2,
        box: 16,
    },
    {
        product_code: 67677,
        wondersoft_code: 23453,
        product_name: 'OVACARE FORTE KIT TAB 1X12',
        warehouse_code: 'HO(1)',
        section: 'A (FWD)',
        lane: 1,
        rack: 'A',
        shelf: 3,
        box: 4,
    },
    {
        product_code: 67677,
        wondersoft_code: 23453,
        product_name: 'ALL 9 TAB 1X15',
        warehouse_code: 'HO(1)',
        section: 'A (FWD)',
        lane: 3,
        rack: 'G',
        shelf: 1,
        box: 25,
    },
    {
        product_code: 67677,
        wondersoft_code: 23453,
        product_name: 'XSTAN 40MG TAB 1X15',
        warehouse_code: 'HO(1)',
        section: 'A (FWD)',
        lane: 4,
        rack: 'F',
        shelf: 5,
        box: 10,
    },
    {
        product_code: 67677,
        wondersoft_code: 23453,
        product_name: 'ZORYL 0.5MG TAB 1X15',
        warehouse_code: 'HO(1)',
        section: 'A (FWD)',
        lane: 2,
        rack: 'R',
        shelf: 3,
        box: 5,
    },
    {
        product_code: 67677,
        wondersoft_code: 23453,
        product_name: 'OPGLIM M 1MG TAB 1X15',
        warehouse_code: 'HO(1)',
        section: 'A (FWD)',
        lane: 5,
        rack: 'P',
        shelf: 3,
        box: 9,
    },
    {
        product_code: 67677,
        wondersoft_code: 23453,
        product_name: 'NICARDIA XL 60MG TAB 1X15',
        warehouse_code: 'HO(1)',
        section: 'A (FWD)',
        lane: 1,
        rack: 'D',
        shelf: 2,
        box: 6,
    },
    {
        product_code: 67677,
        wondersoft_code: 23453,
        product_name: 'GLIMER 1MG TAB 1X15',
        warehouse_code: 'HO(1)',
        section: 'A (FWD)',
        lane: 2,
        rack: 'F',
        shelf: 2,
        box: 12,
    },
    {
        product_code: 67677,
        wondersoft_code: 23453,
        product_name: 'AMLONG TL 40MG TAB 1X10',
        warehouse_code: 'HO(1)',
        section: 'A (FWD)',
        lane: 4,
        rack: 'B',
        shelf: 5,
        box: 4,
    },
    {
        product_code: 67677,
        wondersoft_code: 23453,
        product_name: 'MET XL AM 25/5MG TAB 1X20',
        warehouse_code: 'HO(1)',
        section: 'A (FWD)',
        lane: 5,
        rack: 'H',
        shelf: 2,
        box: 15,
    },
];

const minmaxmaster = [
    {
        product_code: 67677,
        wondersoft_code: 3080,
        product_name: 'FDSON MP D3 TAB 1X10',
        warehouse: 'HO',
        min_value: 2,
        max_value: 20,
        total_stock: 25,
        available: 25,
        reserved: 0,
        on_hold: 0,
    },
    {
        product_code: 68763,
        wondersoft_code: 3280,
        product_name: 'FDSON MP D3 TAB 1X10',
        warehouse: 'HO',
        min_value: 5,
        max_value: 40,
        total_stock: 22,
        available: 22,
        reserved: 0,
        on_hold: 0,
    },
    {
        product_code: 67893,
        wondersoft_code: 3345,
        product_name: 'FDSON MP D3 TAB 1X10',
        warehouse: 'HO',
        min_value: 4,
        max_value: 215,
        total_stock: 30,
        available: 30,
        reserved: 0,
        on_hold: 0,
    },
    {
        product_code: 69087,
        wondersoft_code: 3480,
        product_name: 'FDSON MP D3 TAB 1X10',
        warehouse: 'HO',
        min_value: 1,
        max_value: 10,
        total_stock: 10,
        available: 10,
        reserved: 0,
        on_hold: 0,
    },
    {
        product_code: 67845,
        wondersoft_code: 3345,
        product_name: 'FDSON MP D3 TAB 1X10',
        warehouse: 'HO',
        min_value: 0,
        max_value: 5,
        total_stock: 45,
        available: 45,
        reserved: 0,
        on_hold: 0,
    },
    {
        product_code: 65654,
        wondersoft_code: 2344,
        product_name: 'FDSON MP D3 TAB 1X10',
        warehouse: 'HO',
        min_value: 0,
        max_value: 2,
        total_stock: 36,
        available: 36,
        reserved: 0,
        on_hold: 0,
    },
    {
        product_code: 60980,
        wondersoft_code: 3786,
        product_name: 'FDSON MP D3 TAB 1X10',
        warehouse: 'HO',
        min_value: 3,
        max_value: 30,
        total_stock: 50,
        available: 50,
        reserved: 0,
        on_hold: 0,
    },
    {
        product_code: 62341,
        wondersoft_code: 3654,
        product_name: 'FDSON MP D3 TAB 1X10',
        warehouse: 'HO',
        min_value: 2,
        max_value: 8,
        total_stock: 18,
        available: 18,
        reserved: 0,
        on_hold: 0,
    },
    {
        product_code: 67987,
        wondersoft_code: 3080,
        product_name: 'FDSON MP D3 TAB 1X10',
        warehouse: 'HO',
        min_value: 2,
        max_value: 20,
        total_stock: 56,
        available: 56,
        reserved: 0,
        on_hold: 0,
    },
    {
        product_code: 67677,
        wondersoft_code: 3080,
        product_name: 'FDSON MP D3 TAB 1X10',
        warehouse: 'HO',
        min_value: 2,
        max_value: 20,
        total_stock: 25,
        available: 25,
        reserved: 0,
        on_hold: 0,
    },
];

const moleculemaster = [
    {
        molecule_name: 'PIRFENIDONE 600 MG',
        is_refrigerated: 'Yes',
        scheduled_type_code: 'Schedule',
        ChronicAcute: 'Acute',
        status: 'Published',
    },
    {
        molecule_name: 'METOPROLOL SUCCINATE 12.5 MG SUSTAINED REL',
        is_refrigerated: 'No',
        scheduled_type_code: 'Schedule',
        ChronicAcute: 'Acute',
        status: 'Published',
    },
    {
        molecule_name: 'FLUVOXAMINE 100 MG CONTROLLED RELEASE',
        is_refrigerated: 'No',
        scheduled_type_code: 'Schedule',
        ChronicAcute: 'Acute',
        status: 'Published',
    },
    {
        molecule_name: 'FLUVOXAMINE 100 MG CONTROLLED RELEASE',
        is_refrigerated: 'No',
        scheduled_type_code: 'Schedule',
        ChronicAcute: 'Acute',
        status: 'Published',
    },
    {
        molecule_name: 'PARACETAMOL/ACETAMINOPHEN 650 MG SUSTAINED RELEASE',
        is_refrigerated: 'No',
        scheduled_type_code: 'Non Schedule',
        ChronicAcute: 'Acute',
        status: 'Published',
    },
    {
        molecule_name: 'VILDAGLIPTIN 50 MG SUSTAINED RELEASE',
        is_refrigerated: 'No',
        scheduled_type_code: 'Non Schedule',
        ChronicAcute: 'Chronic',
        status: 'Published',
    },
    {
        molecule_name: 'DOMPERIDONE 30 MG SUSTAINED RELEASE',
        is_refrigerated: 'No',
        scheduled_type_code: 'Schedule',
        ChronicAcute: 'Acute',
        status: 'Published',
    },
    {
        molecule_name: 'NITROFURANTOIN 100 MG SUSTAINED RELEASE',
        is_refrigerated: 'No',
        scheduled_type_code: 'Non Schedule',
        ChronicAcute: 'Acute',
        status: 'Published',
    },
    {
        molecule_name: 'PHENYTOIN 300 MG SUSTAINED RELEASE',
        is_refrigerated: 'No',
        scheduled_type_code: 'Schedule',
        ChronicAcute: 'Chronic',
        status: 'Published',
    },
    {
        molecule_name: 'DOXOFYLLINE 650 MG SUSTAINED RELEASE',
        is_refrigerated: 'No',
        scheduled_type_code: 'Schedule',
        ChronicAcute: 'Chronic',
        status: 'Published',
    },
];

const manufacturemaster = [
    {
        manufacturer_name: 'DEEPP',
        created_by: 'System (19-06-2023 2:42 PM)',
        updated_by: 'WMS (14-07-2023 11:21 AM)',
        status: 'Draft'
    },
    {
        manufacturer_name: 'A. MENARINI INDIA PRIVATE LIMITED',
        created_by: 'System (19-06-2023 2:42 PM)',
        updated_by: 'WMS (14-07-2023 11:21 AM)',
        status: 'Draft'
    },
    {
        manufacturer_name: 'INNOVCARE LIFESCIENCES PRIVATE LIMITED',
        created_by: 'System (19-06-2023 2:42 PM)',
        updated_by: '(-)',
        status: 'Published'
    },
    {
        manufacturer_name: 'SWADESH LIFE SCIENCE',
        created_by: 'System (19-06-2023 2:42 PM)',
        updated_by: '(-)',
        status: 'Published'
    },
    {
        manufacturer_name: 'INCY HEALTHCARE PVT LTD',
        created_by: 'System (19-06-2023 2:42 PM)',
        updated_by: '(-)',
        status: 'Published'
    },
    {
        manufacturer_name: 'MEDIMARCK BIOTECH PVT LTD',
        created_by: 'System (19-06-2023 2:42 PM)',
        updated_by: '(-)',
        status: 'Published'
    },
    {
        manufacturer_name: 'MASCOT HEALTH SERIES PVT LTD',
        created_by: 'System (19-06-2023 2:42 PM)',
        updated_by: '(-)',
        status: 'Published'
    },
    {
        manufacturer_name: 'ADONIS LABORATORIES PVT LTD',
        created_by: 'System (19-06-2023 2:42 PM)',
        updated_by: '(-)',
        status: 'Published'
    },
    {
        manufacturer_name: 'BEIERSDORF INDIA LTD',
        created_by: 'System (19-06-2023 2:42 PM)',
        updated_by: '(-)',
        status: 'Published'
    },
    {
        manufacturer_name: 'INVASION PHARMACEUTICALS PVT LTD',
        created_by: 'System (19-06-2023 2:42 PM)',
        updated_by: '(-)',
        status: 'Published'
    },
];

const vendormaster = [
    {
        vendor_name: 'vendor check',
        contact_name: '-',
        contact_mobile: 9876543210,
        contact_email: 'test@test.com',
        status: 'Draft',
    },
    {
        vendor_name: 'sample vendor data',
        contact_name: '-',
        contact_mobile: 9876543210,
        contact_email: 'test@test.com',
        status: 'Draft',
    },
    {
        vendor_name: 'SHREE',
        contact_name: 'Deep',
        contact_mobile: 9876543210,
        contact_email: 'sample@testmail.com',
        status: 'Published',
    },
    {
        vendor_name: 'HARDIK DISTRIBUTORS',
        contact_name: 'HARDIK DISTRIBUTORS',
        contact_mobile: 9876543210,
        contact_email: 'sample@testmail.com',
        status: 'Published',
    },
    {
        vendor_name: 'TO BE deL',
        contact_name: 'K B SHAH AND',
        contact_mobile: 9876543210,
        contact_email: 'sample@testmail.com',
        status: 'Published',
    },
    {
        vendor_name: 'DHRUVI PHARMA PVT LTD',
        contact_name: 'DHRUVI PHARMA PVT LTD',
        contact_mobile: 9876543210,
        contact_email: 'sample@testmail.com',
        status: 'Published',
    },
    {
        vendor_name: 'ATHARVA BIO PRODUCTS',
        contact_name: 'ATHARVA BIO PRODUCTS',
        contact_mobile: 9876543210,
        contact_email: 'sample@testmail.com',
        status: 'Published',
    },
    {
        vendor_name: 'ZYMO BEAUTY SCIENCE PRIVATE LIMITED',
        contact_name: 'ZYMO BEAUTY SCIENCE PRIVATE LIMITED',
        contact_mobile: 9876543210,
        contact_email: 'sample@testmail.com',
        status: 'Published',
    },
    {
        vendor_name: 'DAYNACARE LIFESCIENCE',
        contact_name: 'DAYNACARE LIFESCIENCE',
        contact_mobile: 9876543210,
        contact_email: 'sample@testmail.com',
        status: 'Published',
    },
    {
        vendor_name: 'SUPAL PHARMA',
        contact_name: 'SUPAL PHARMA',
        contact_mobile: 9876543210,
        contact_email: 'sample@testmail.com',
        status: 'Published',
    },
];

const productchannelmapping = [
    {
        product_code: 56739,
        wondersoft_code: 12342,
        product_name: 'GLICDUO XR 60/500MG TAB 1X10',
        vendor_name: '-',
        product_channel: 'PHARMA_RACK'
    },
    {
        product_code: 56244,
        wondersoft_code: 18743,
        product_name: 'SITASON 50MG TAB 1X10',
        vendor_name: '-',
        product_channel: 'UNISON'
    },
    {
        product_code: 56241,
        wondersoft_code: 12342,
        product_name: 'NULONG MT 25MG TAB 1X10',
        vendor_name: '-',
        product_channel: 'PHARMA_RACK'
    },
    {
        product_code: 56745,
        wondersoft_code: 18777,
        product_name: 'BITATEL M 3D 12.5/25/40MG TAB 1X10',
        vendor_name: '-',
        product_channel: 'PHARMA_RACK'
    },
    {
        product_code: 56876,
        wondersoft_code: 18465,
        product_name: 'M SOLVIN TAB 1X10',
        vendor_name: '-',
        product_channel: 'PHARMA_RACK'
    },
    {
        product_code: 56765,
        wondersoft_code: 18456,
        product_name: 'NEFVIT PLUS TAB 1X10',
        vendor_name: '-',
        product_channel: 'PHARMA_RACK'
    },
    {
        product_code: 56443,
        wondersoft_code: 17674,
        product_name: 'RABIFAST DSR CAP 1X15',
        vendor_name: '-',
        product_channel: 'PHARMA_RACK'
    },
    {
        product_code: 56739,
        wondersoft_code: 12442,
        product_name: 'NEUROKEM OD 75MG TAB 1X10',
        vendor_name: '-',
        product_channel: 'PHARMA_RACK'
    },
    {
        product_code: 56744,
        wondersoft_code: 14874,
        product_name: 'MORISONS SILICON NIPPLE ( MEDIUM )',
        vendor_name: '-',
        product_channel: 'OTHER'
    },
    {
        product_code: 56743,
        wondersoft_code: 17874,
        product_name: 'MORISONS POLY FEDER 125ML',
        vendor_name: '-',
        product_channel: 'OTHER'
    },
];

const b2cPricingMaster = [
    {
        category_name: 'Disc 30 Perc',
        discount: '30%',
        status:'',
    },
    {
        category_name: 'Launch Category',
        discount: '30%',
        status:'',
    },
    {
        category_name: 'Disc 25 Perc',
        discount: '25%',
        status:'',
    },
    {
        category_name: 'Disc 20 Perc',
        discount: '20%',
        status:'',
    },
    {
        category_name: 'Disc 15 Perc',
        discount: '15%',
        status:'',
    },
    {
        category_name: 'Disc 10 Perc',
        discount: '10%',
        status:'',
    },
    {
        category_name: 'Disc 5 Perc',
        discount: '5%',
        status:'',
    },
    {
        category_name: 'Disc 0 Perc',
        discount: '0%',
        status:'',
    },
    {
        category_name: 'Disc 40 Perc',
        discount: '40%',
        status:'',
    },
    {
        category_name: 'Disc 35 Perc',
        discount: '35%',
        status:'',
    },
];

const storeMaster = [
    {
        wondersoft_store_ID: 23,
        store_name: 'PURAV & ASSOCIATES',
        city: 'VADODARA',
        type: 'FOFO',
        status: 'Active',
    },
    {
        wondersoft_store_ID: 20,
        store_name: 'AKSHAR PHARMACY',
        city: 'AHMEDABAD',
        type: 'FOFO',
        status: 'Active',
    },
    {
        wondersoft_store_ID: 18,
        store_name: 'B&G ENTERPRISE',
        city: 'VADODARA',
        type: 'FOFO',
        status: 'Inactive',
    },
    {
        wondersoft_store_ID: 21,
        store_name: 'BK ENTERPRISE',
        city: 'VADODARA',
        type: 'FOFO',
        status: 'Active',
    },
    {
        wondersoft_store_ID: 40,
        store_name: 'FOSTEROOH ENTERPRISES LLP',
        city: 'AHMEDABAD',
        type: 'FOFO',
        status: 'Active',
    },
    {
        wondersoft_store_ID: 2,
        store_name: 'K AND T ASSOCIATE',
        city: 'VADODARA',
        type: 'FOFO',
        status: 'Inactive',
    },
    {
        wondersoft_store_ID: 30,
        store_name: 'MEDONE PHARMACY',
        city: 'AHMEDABAD',
        type: 'FOFO',
        status: 'Active',
    },
    {
        wondersoft_store_ID: 12,
        store_name: 'SHREE HARI MEDICAL',
        city: 'VADODARA',
        type: 'FOFO',
        status: 'Active',
    },
    {
        wondersoft_store_ID: 9,
        store_name: 'SANJIVANI MEDICAL',
        city: 'VADODARA',
        type: 'FOFO',
        status: 'Inactive',
    },
    {
        wondersoft_store_ID: 5,
        store_name: 'SANJIVANI PHARMACY',
        city: 'VADODARA',
        type: 'FOFO',
        status: 'Active',
    },
];

const warehousemaster = [
    {
        warehouse_code: 1,
        warehouse_name: 'HO',
        city: 'Ahmedabad',
        type: 'Owned',
        status: 'Active'
    }
];

const MrpPtrData = [
    {
        product_code: 56436,
        wonderSoft_code: 3763,
        product_name: 'FEBIRED TAB 1X15',
        MRP: '₹117',
        mRP_PTR_ratio: 0.80000,
    },
    {
        product_code: 87659,
        wonderSoft_code: 7845,
        product_name: 'NS INJ 1000ML',
        MRP: '₹23',
        mRP_PTR_ratio: 0.0256,
    },
    {
        product_code: 54837,
        wonderSoft_code: 4763,
        product_name: 'OMILCAL SYP 200ML',
        MRP: '₹2',
        mRP_PTR_ratio: 0.4582,
    },
    {
        product_code: 89734,
        wonderSoft_code: 6763,
        product_name: 'LUMIGAN 0.01% DROPS 3ML',
        MRP: '₹121',
        mRP_PTR_ratio: 0.54285,
    },
    {
        product_code: 50987,
        wonderSoft_code: 9898,
        product_name: 'THYRONORM 75MCG TAB 1X120',
        MRP: '₹5',
        mRP_PTR_ratio: 0.5438,
    },
    {
        product_code: 5635,
        wonderSoft_code: 1263,
        product_name: 'AMODEP AT TAB 1X15',
        MRP: '₹10',
        mRP_PTR_ratio: 0.53553,
    },
    {
        product_code: 12436,
        wonderSoft_code: 3963,
        product_name: 'FLAMINGO TENNIS ELBOW SUPPORT',
        MRP: '₹90',
        mRP_PTR_ratio: 0.5655,
    },
    {
        product_code: 90436,
        wonderSoft_code: 3778,
        product_name: 'DAFLON 1000MG TAB 1X18',
        MRP: '₹121',
        mRP_PTR_ratio: 0.8946,
    },
    {
        product_code: 12336,
        wonderSoft_code: 8963,
        product_name: 'ONABET SD SOLUTION 15ML',
        MRP: '₹100',
        mRP_PTR_ratio: 0.248841,
    },
    {
        product_code: 76436,
        wonderSoft_code: 3908,
        product_name: 'FEBIRED TAB 1X15',
        MRP: '₹1',
        mRP_PTR_ratio: 0.8344,
    },
];

const stockadjustment = [
    {
        adj_no: 'SA101001009',
        date: '18-07-2023',
        type: 'Stock Adjustment',
        total_items: '2',
        total_adjusted_qty: '102',
        created_by: 'Raj Busa',
        approved_by_rejected_by: 'Jenil Kundaliya (20-07-2023 6:25 PM)',
        status: 'Approved',
    },
    {
        adj_no: 'SA101001008',
        date: '18-07-2023',
        type: 'Stock Adjustment',
        total_items: 3,
        total_adjusted_qty: 100,
        created_by: 'Raj Busa',
        approved_by_rejected_by: 'Jenil Kundaliya (20-07-2023 6:25 PM)',
        status: 'Draft',
    },
    {
        adj_no: 'SA101001007',
        date: '18-07-2023',
        type: 'Stock Adjustment',
        total_items: 3,
        total_adjusted_qty: 300,
        created_by: 'Raj Busa',
        approved_by_rejected_by: 'System User (05-07-2023 2:39 PM)',
        status: 'Approved',
    },
    {
        adj_no: 'SA101001006',
        date: '17-07-2023',
        type: 'Stock Adjustment',
        total_items: 1,
        total_adjusted_qty: 4000,
        created_by: 'Raj Busa',
        approved_by_rejected_by: 'System User (11-07-2023 3:53 PM)',
        status: 'Approved',
    },
    {
        adj_no: 'SA101001005',
        date: '17-07-2023',
        type: 'Stock Adjustment',
        total_items: 1,
        total_adjusted_qty: 10500,
        created_by: 'Raj Busa',
        approved_by_rejected_by: 'Narendra Chandel (14-07-2023 7:08 PM)',
        status: 'Draft',
    },
    {
        adj_no: 'SA101001004',
        date: '17-07-2023',
        type: 'Stock Adjustment',
        total_items: 1,
        total_adjusted_qty: 2000,
        created_by: 'Raj Busa',
        approved_by_rejected_by: 'Jenil Kundaliya (17-07-2023 11:26 AM)',
        status: 'Approved',
    },
    {
        adj_no: 'SA101001003',
        date: '17-07-2023',
        type: 'Stock Adjustment',
        total_items: 21,
        total_adjusted_qty: 25,
        created_by: 'Raj Busa',
        approved_by_rejected_by: 'Jenil Kundaliya (17-07-2023 11:39 AM)',
        status: 'Approved',
    },
    {
        adj_no: 'SA101001002',
        date: '17-07-2023',
        type: 'Stock Adjustment',
        total_items: 2,
        total_adjusted_qty: 30,
        created_by: 'Raj Busa',
        approved_by_rejected_by: 'Jenil Kundaliya (04-09-2023 4:39 PM)',
        status: 'Draft',
    },
    {
        adj_no: 'SA101001001',
        date: '14-07-2023',
        type: 'Stock Adjustment',
        total_items: 272,
        total_adjusted_qty: 15500,
        created_by: 'Raj Busa',
        approved_by_rejected_by: 'Jenil Kundaliya (17-07-2023 11:40 AM)',
        status: 'Approved',
    },
    {
        adj_no: 'SA101001000',
        date: '11-07-2023',
        type: 'Stock Adjustment',
        total_items: 72,
        total_adjusted_qty: 400,
        created_by: 'Raj Busa',
        approved_by_rejected_by: 'Jenil Kundaliya (04-09-2023 4:40 PM)',
        status: 'Draft',
    },
];

const stockrearrange = [
    {
        assingned_by_name: 'Pujan M',
        checker_name: 'Rajdeep H',
        rack_assigned: 'D',
        lane_assigned: '7',
        total_products: '78',
        assigned_at: '20/09/2023 06:06 PM',
        started_at: '-',
        complete_at: '-',
        no_of_queries: '-',
        found_product: '50',
        not_found_product: '-',
        new_product: '-',
        status: 'Pending',
    },
    {
        assingned_by_name: 'Hiren C',
        checker_name: 'Rajdeep H',
        rack_assigned: 'A',
        lane_assigned: '2',
        total_products: '120',
        assigned_at: '20/09/2023 06:06 PM',
        started_at: '-',
        complete_at: '31/08/2023 04:51 PM',
        no_of_queries: '-',
        found_product: '-',
        not_found_product: '-',
        new_product: '8',
        status: 'Pending',
    },
    {
        assingned_by_name: 'Pujan M',
        checker_name: 'Pujan M',
        rack_assigned: 'S',
        lane_assigned: '2',
        total_products: '40',
        assigned_at: '20/09/2023 06:06 PM',
        started_at: '-',
        complete_at: '31/08/2023 04:51 PM',
        no_of_queries: '-',
        found_product: '60',
        not_found_product: '-',
        new_product: '-',
        status: 'In Progress',
    },
    {
        assingned_by_name: 'Hiren C',
        checker_name: 'Pujan M',
        rack_assigned: 'F',
        lane_assigned: '4',
        total_products: '80',
        assigned_at: '20/09/2023 06:06 PM',
        started_at: '-',
        complete_at: '31/08/2023 04:51 PM',
        no_of_queries: '-',
        found_product: '-',
        not_found_product: '-',
        new_product: '3',
        status: 'In Progress',
    },
    {
        assingned_by_name: 'Pujan M',
        checker_name: 'Pujan M',
        rack_assigned: 'H',
        lane_assigned: '2',
        total_products: '150',
        assigned_at: '20/09/2023 06:06 PM',
        started_at: '20/09/2023 05:33 PM',
        complete_at: '31/08/2023 04:51 PM',
        no_of_queries: '-',
        found_product: '30',
        not_found_product: '-',
        new_product: '-',
        status: 'In Progress',
    },
    {
        assingned_by_name: 'Hiren C',
        checker_name: 'Pujan M',
        rack_assigned: 'G',
        lane_assigned: '1',
        total_products: '90',
        assigned_at: '20/09/2023 06:06 PM',
        started_at: '20/09/2023 05:33 PM',
        complete_at: '-',
        no_of_queries: '2',
        found_product: '-',
        not_found_product: '-',
        new_product: '6',
        status: 'In Progress',
    },
    {
        assingned_by_name: 'Rajdeep H',
        checker_name: 'Rajdeep H',
        rack_assigned: 'J',
        lane_assigned: '2',
        total_products: '38',
        assigned_at: '20/09/2023 06:06 PM',
        started_at: '20/09/2023 05:33 PM',
        complete_at: '-',
        no_of_queries: '-',
        found_product: '-',
        not_found_product: '-',
        new_product: '-',
        status: 'In Progress',
    },
    {
        assingned_by_name: 'Pujan M',
        checker_name: 'Rajdeep H',
        rack_assigned: 'K',
        lane_assigned: '5',
        total_products: '70',
        assigned_at: '20/09/2023 06:06 PM',
        started_at: '20/09/2023 05:33 PM',
        complete_at: '-',
        no_of_queries: '1',
        found_product: '10',
        not_found_product: '-',
        new_product: '-',
        status: 'Completed',
    },
    {
        assingned_by_name: 'Rajdeep H',
        checker_name: 'Rajdeep H',
        rack_assigned: 'L',
        lane_assigned: '4',
        total_products: '60',
        assigned_at: '20/09/2023 06:06 PM',
        started_at: '-',
        complete_at: '-',
        no_of_queries: '4',
        found_product: '-',
        not_found_product: '-',
        new_product: '4',
        status: 'Completed',
    },
    {
        assingned_by_name: 'Pujan M',
        checker_name: 'Rajdeep H',
        rack_assigned: 'R',
        lane_assigned: '2',
        total_products: '10',
        assigned_at: '20/09/2023 06:06 PM',
        started_at: '20/09/2023 05:33 PM',
        complete_at: '31/08/2023 04:51 PM',
        no_of_queries: '3',
        found_product: '-',
        not_found_product: '-',
        new_product: '10',
        status: 'Completed',
    },
];

const reallocation = [
    {
        file_name: 'REALLOCATION_250',
        upload_by: '(Jul 24-2023 2:56 PM)',
        no_of_records: '2',
        total_qty_ordered: '8',
        total_qty_fulfiled: '8',
        PN_generated_time: '24-Jul-2023 02:57:05 PM',
        status: '-',
    },
    {
        file_name: 'REALLOCATION_235',
        upload_by: '(Jul 24-2023 2:56 PM)',
        no_of_records: '-',
        total_qty_ordered: '-',
        total_qty_fulfiled: '0',
        PN_generated_time: '24-Jul-2023 02:57:05 PM',
        status: 'Processed',
    },
    {
        file_name: 'REALLOCATION_267',
        upload_by: '(Jul 24-2023 2:56 PM)',
        no_of_records: '5',
        total_qty_ordered: '7',
        total_qty_fulfiled: '9',
        PN_generated_time: '24-Jul-2023 02:57:05 PM',
        status: '-',
    },
    {
        file_name: 'REALLOCATION_237',
        upload_by: '(Jul 24-2023 2:56 PM)',
        no_of_records: '1',
        total_qty_ordered: '4',
        total_qty_fulfiled: '10',
        PN_generated_time: '24-Jul-2023 02:57:05 PM',
        status: 'Processed',
    },
    {
        file_name: 'REALLOCATION_298',
        upload_by: '(Jul 24-2023 2:56 PM)',
        no_of_records: '6',
        total_qty_ordered: '17',
        total_qty_fulfiled: '10',
        PN_generated_time: '24-Jul-2023 02:57:05 PM',
        status: 'Processed',
    },
    {
        file_name: 'REALLOCATION_209',
        upload_by: '(Jul 24-2023 2:56 PM)',
        no_of_records: '5',
        total_qty_ordered: '5',
        total_qty_fulfiled: '7',
        PN_generated_time: '24-Jul-2023 02:57:05 PM',
        status: 'Processed',
    },
    {
        file_name: 'REALLOCATION_247',
        upload_by: '(Jul 24-2023 2:56 PM)',
        no_of_records: '6',
        total_qty_ordered: '9',
        total_qty_fulfiled: '4',
        PN_generated_time: '24-Jul-2023 02:57:05 PM',
        status: 'Processed',
    },
    {
        file_name: 'REALLOCATION_287',
        upload_by: '(Jul 24-2023 2:56 PM)',
        no_of_records: '4',
        total_qty_ordered: '3',
        total_qty_fulfiled: '0',
        PN_generated_time: '24-Jul-2023 02:57:05 PM',
        status: 'Processed',
    },
    {
        file_name: 'REALLOCATION_212',
        upload_by: '(Jul 24-2023 2:56 PM)',
        no_of_records: '6',
        total_qty_ordered: '6',
        total_qty_fulfiled: '3',
        PN_generated_time: '24-Jul-2023 02:57:05 PM',
        status: 'Processed',
    },
    {
        file_name: 'REALLOCATION_234',
        upload_by: '(Jul 24-2023 2:56 PM)',
        no_of_records: '4',
        total_qty_ordered: '9',
        total_qty_fulfiled: '10',
        PN_generated_time: '24-Jul-2023 02:57:05 PM',
        status: 'Processed',
    },
];

const transferout = [
    {
        date: '20-09-2023',
        STN_no: 'TO101001012',
        store_code: '127',
        store_name: 'MEDKART AN JITO',
        city_name: 'ANAND',
        total_products: 1,
        total_qty: 2,
        MRP_total: '₹123.27',
        invoice_by: 'Pratibha T',
        status: 'Generated',
    },
    {
        date: '24-07-2023',
        STN_no: 'TO101001011',
        store_code: '122',
        store_name: 'MEDKART G KUD',
        city_name: 'GANDHINAGAR',
        total_products: 2,
        total_qty: 1,
        MRP_total: '₹842.35',
        invoice_by: 'System User',
        status: 'Generated',
    },
    {
        date: '19-07-2023',
        STN_no: 'TO101001010',
        store_code: '122',
        store_name: 'MEDKART G KUDAS',
        city_name: 'GANDHINAGAR',
        total_products: 1,
        total_qty: 6,
        MRP_total: '₹127.68',
        invoice_by: 'Pratibha T',
        status: 'Generated',
    },
    {
        date: '18-09-2023',
        STN_no: 'TO101001009',
        store_code: '125',
        store_name: 'J M AND K ENTERP',
        city_name: 'Ahmedabad',
        total_products: 1,
        total_qty: 3,
        MRP_total: '₹4480',
        invoice_by: 'Rajan',
        status: 'Generated',
    },
    {
        date: '17-09-2023',
        STN_no: 'TO101001008',
        store_code: '56',
        store_name: 'MEDKART B KARELIBAG',
        city_name: 'Ahmedabad',
        total_products: 2,
        total_qty: 15,
        MRP_total: '₹0.01',
        invoice_by: 'System User',
        status: 'Generated',
    },
    {
        date: '17-09-2023',
        STN_no: 'TO101001007',
        store_code: '78',
        store_name: '	MEDKART A PRERNATIRTH',
        city_name: 'VADODARA',
        total_products: 1,
        total_qty: 7,
        MRP_total: '₹441.3',
        invoice_by: 'System User',
        status: 'Generated',
    },
    {
        date: '17-09-2023',
        STN_no: 'TO101001006',
        store_code: '12',
        store_name: 'MEDKART AN JITO',
        city_name: 'VADODARA',
        total_products: 2,
        total_qty: 45,
        MRP_total: '₹93.49',
        invoice_by: 'Rajan',
        status: 'Generated',
    },
    {
        date: '16-09-2023',
        STN_no: 'TO101001005',
        store_code: '10',
        store_name: 'MEDKART AN JITO',
        city_name: 'VAPI',
        total_products: 1,
        total_qty: 9,
        MRP_total: '₹123.27',
        invoice_by: 'System User',
        status: 'Generated',
    },
    {
        date: '16-09-2023',
        STN_no: 'TO101001004',
        store_code: '6',
        store_name: 'MEDKART AN JITO',
        city_name: 'VAPI',
        total_products: 1,
        total_qty: 12,
        MRP_total: '₹123.27',
        invoice_by: 'System User',
        status: 'Generated',
    },
    {
        date: '16-09-2023',
        STN_no: 'TO101001003',
        store_code: '9',
        store_name: 'MEDKART AN JITO',
        city_name: 'ANAND',
        total_products: 2,
        total_qty: 10,
        MRP_total: '₹123.27',
        invoice_by: 'System User',
        status: 'Generated',
    },
];

const internalsales = [
    {
        date: '20-09-2023',
        invoice_no: 'IS101001034',
        store_code: '127',
        store_name: 'MEDKART AN JITO',
        city_name: 'ANAND',
        total_products: 1,
        total_qty: 2,
        MRP_total: '₹123.27',
        invoice_by: 'Pratibha T',
        status: 'Generated',
    },
    {
        date: '24-07-2023',
        invoice_no: 'IS101001055',
        store_code: '122',
        store_name: 'MEDKART G KUD',
        city_name: 'GANDHINAGAR',
        total_products: 2,
        total_qty: 1,
        MRP_total: '₹842.35',
        invoice_by: 'System User',
        status: 'Generated',
    },
    {
        date: '19-07-2023',
        invoice_no: 'IS101001043',
        store_code: '122',
        store_name: 'MEDKART G KUDAS',
        city_name: 'GANDHINAGAR',
        total_products: 1,
        total_qty: 6,
        MRP_total: '₹127.68',
        invoice_by: 'Pratibha T',
        status: 'Generated',
    },
    {
        date: '18-09-2023',
        invoice_no: 'IS101001076',
        store_code: '125',
        store_name: 'J M AND K ENTERP',
        city_name: 'Ahmedabad',
        total_products: 1,
        total_qty: 3,
        MRP_total: '₹4480',
        invoice_by: 'Rajan',
        status: 'Generated',
    },
    {
        date: '17-09-2023',
        invoice_no: 'IS101001045',
        store_code: '56',
        store_name: 'MEDKART B KARELIBAG',
        city_name: 'Ahmedabad',
        total_products: 2,
        total_qty: 15,
        MRP_total: '₹0.01',
        invoice_by: 'System User',
        status: 'Generated',
    },
    {
        date: '17-09-2023',
        invoice_no: 'IS101001007',
        store_code: '78',
        store_name: '	MEDKART A PRERNATIRTH',
        city_name: 'VADODARA',
        total_products: 1,
        total_qty: 7,
        MRP_total: '₹441.3',
        invoice_by: 'System User',
        status: 'Generated',
    },
    {
        date: '17-09-2023',
        invoice_no: 'IS101001098',
        store_code: '12',
        store_name: 'MEDKART AN JITO',
        city_name: 'VADODARA',
        total_products: 2,
        total_qty: 45,
        MRP_total: '₹93.49',
        invoice_by: 'Rajan',
        status: 'Generated',
    },
    {
        date: '16-09-2023',
        invoice_no: 'IS101001078',
        store_code: '10',
        store_name: 'MEDKART AN JITO',
        city_name: 'VAPI',
        total_products: 1,
        total_qty: 9,
        MRP_total: '₹123.27',
        invoice_by: 'System User',
        status: 'Generated',
    },
    {
        date: '16-09-2023',
        invoice_no: 'IS101001024',
        store_code: '6',
        store_name: 'MEDKART AN JITO',
        city_name: 'VAPI',
        total_products: 1,
        total_qty: 12,
        MRP_total: '₹123.27',
        invoice_by: 'System User',
        status: 'Generated',
    },
    {
        date: '16-09-2023',
        invoice_no: 'IS101001056',
        store_code: '9',
        store_name: 'MEDKART AN JITO',
        city_name: 'ANAND',
        total_products: 2,
        total_qty: 10,
        MRP_total: '₹123.27',
        invoice_by: 'System User',
        status: 'Generated',
    },
];

const b2csales = [
    {
        date: '20-09-2023',
        invoice_no: 'IS101001034',
        SO_no: '',
        sales_ref_no: '',
        pick_note: 'PS10100107',
        customer_name: 'BharatBhai',
        total_products: 1,
        total_qty: 2,
        invoice_total: '₹123.27',
        due_amount: '₹136.82',
        invoice_by: 'Pratibha T',
        payment_status: 'Partially Paid',
    },
    {
        date: '24-07-2023',
        invoice_no: 'IS101001055',
        SO_no: '',
        sales_ref_no: '',
        pick_note: 'PS10100107',
        customer_name: 'BharatBhai',
        total_products: 2,
        total_qty: 1,
        invoice_total: '₹842.35',
        due_amount: '₹136.82',
        invoice_by: 'System User',
        payment_status: 'Fully Paid',
    },
    {
        date: '19-07-2023',
        invoice_no: 'IS101001043',
        SO_no: '',
        sales_ref_no: '',
        pick_note: 'PS10100107',
        customer_name: 'BharatBhai',
        total_products: 1,
        total_qty: 6,
        invoice_total: '₹127.68',
        due_amount: '₹136.82',
        invoice_by: 'Pratibha T',
        payment_status: 'Partially Paid',
    },
    {
        date: '18-09-2023',
        invoice_no: 'IS101001076',
        SO_no: '',
        sales_ref_no: '',
        pick_note: 'PS10100107',
        customer_name: 'BharatBhai',
        total_products: 1,
        total_qty: 3,
        invoice_total: '₹4480',
        due_amount: '₹136.82',
        invoice_by: 'Rajan',
        payment_status: 'Fully Paid',
    },
    {
        date: '17-09-2023',
        invoice_no: 'IS101001045',
        SO_no: '',
        sales_ref_no: '',
        pick_note: 'PS10100107',
        customer_name: 'BharatBhai',
        total_products: 2,
        total_qty: 15,
        invoice_total: '₹0.01',
        due_amount: '₹136.82',
        invoice_by: 'System User',
        payment_status: 'UnPaid',
    },
    {
        date: '17-09-2023',
        invoice_no: 'IS101001007',
        SO_no: '',
        sales_ref_no: '',
        pick_note: 'PS10100107',
        customer_name: 'BharatBhai',
        total_products: 1,
        total_qty: 7,
        invoice_total: '₹441.3',
        due_amount: '₹136.82',
        invoice_by: 'System User',
        payment_status: 'Partially Paid',
    },
    {
        date: '17-09-2023',
        invoice_no: 'IS101001098',
        SO_no: '',
        sales_ref_no: '',
        pick_note: 'PS10100107',
        customer_name: 'BharatBhai',
        total_products: 2,
        total_qty: 45,
        invoice_total: '₹93.49',
        due_amount: '₹136.82',
        invoice_by: 'Rajan',
        payment_status: 'UnPaid',
    },
    {
        date: '16-09-2023',
        invoice_no: 'IS101001078',
        SO_no: '',
        sales_ref_no: '',
        pick_note: 'PS10100107',
        customer_name: 'BharatBhai',
        total_products: 1,
        total_qty: 9,
        invoice_total: '₹123.27',
        due_amount: '₹136.82',
        invoice_by: 'System User',
        payment_status: 'Fully Paid',
    },
    {
        date: '16-09-2023',
        invoice_no: 'IS101001024',
        SO_no: '',
        sales_ref_no: '',
        pick_note: 'PS10100107',
        customer_name: 'BharatBhai',
        total_products: 1,
        total_qty: 12,
        invoice_total: '₹123.27',
        due_amount: '₹136.82',
        invoice_by: 'System User',
        payment_status: 'UnPaid',
    },
    {
        date: '16-09-2023',
        invoice_no: 'IS101001056',
        SO_no: '',
        sales_ref_no: '',
        pick_note: 'PS10100107',
        customer_name: 'BharatBhai',
        total_products: 2,
        total_qty: 10,
        invoice_total: '₹123.27',
        due_amount: '₹136.82',
        invoice_by: 'System User',
        payment_status: 'UnPaid',
    },
];

const checkingtracker = [
    {
        gate_pass_no: 'GP101001031',
        inward_date_time: '20-09-2023 3:43 PM',
        vendor_name: 'M K ENTERPRISE',
        invoice_no: '451',
        invoice_amount: '₹4824',
        invoice_qty: '3',
        no_of_SKU: '3',
        start_time: '12:00 AM',
        end_time: '01:00 AM',
        checker_name: 'Pratibha T',
        status: 'Completed',
    },
    {
        gate_pass_no: 'GP101001010',
        inward_date_time: '18-09-2023 1:43 PM',
        vendor_name: 'VACCINE POINT',
        invoice_no: '232GHJ',
        invoice_amount: '₹500',
        invoice_qty: '2',
        no_of_SKU: '4',
        start_time: '12:00 AM',
        end_time: '01:00 AM',
        checker_name: 'Harshil R',
        status: 'Completed',
    },
    {
        gate_pass_no: 'GP101001020',
        inward_date_time: '16-09-2023 5:43 PM',
        vendor_name: 'M K ENTERPRISE',
        invoice_no: '345',
        invoice_amount: '₹1000',
        invoice_qty: '4',
        no_of_SKU: '2',
        start_time: '12:00 AM',
        end_time: '01:00 AM',
        checker_name: 'Pratibha T',
        status: 'Uncomplet',
    },
];

const grn = [
    {
        GRN_number: 'GR101001020',
        GRN_date_time: '20/09/2023 3:43:57 PM',
        invoice_date: '20-09-2023',
        invoice_number: 'IS101001034',
        vendor_name: 'BharatBhai',
        total_products: 1,
        total_qty: 2,
        total_amount: '₹123.27',
        MRP_total: '₹136.82',
        on_hold_by: 'Pratibha T',
        confirmed_by: 'Pratibha T',
        status: 'Invoiced',
    },
    {
        GRN_number: 'GR101001020',
        GRN_date_time: '20/09/2023 3:43:57 PM',
        invoice_date: '24-07-2023',
        invoice_number: 'IS101001055',
        vendor_name: 'BharatBhai',
        total_products: 2,
        total_qty: 1,
        total_amount: '₹842.35',
        MRP_total: '₹136.82',
        on_hold_by: '-',
        confirmed_by: '-',
        status: 'On Hold',
    },
    {
        GRN_number: 'GR101001020',
        GRN_date_time: '20/09/2023 3:43:57 PM',
        invoice_date: '19-07-2023',
        invoice_number: 'IS101001043',
        vendor_name: 'BharatBhai',
        total_products: 1,
        total_qty: 6,
        total_amount: '₹127.68',
        MRP_total: '₹136.82',
        on_hold_by: '-',
        confirmed_by: '-',
        status: 'Invoiced',
    },
    {
        GRN_number: 'GR101001020',
        GRN_date_time: '20/09/2023 3:43:57 PM',
        invoice_date: '18-09-2023',
        invoice_number: 'IS101001076',
        vendor_name: 'BharatBhai',
        total_products: 1,
        total_qty: 3,
        total_amount: '₹4480',
        MRP_total: '₹136.82',
        on_hold_by: '-',
        confirmed_by: '-',
        status: 'Invoiced',
    },
    {
        GRN_number: 'GR101001020',
        GRN_date_time: '20/09/2023 3:43:57 PM',
        invoice_date: '17-09-2023',
        invoice_number: 'IS101001045',
        vendor_name: 'BharatBhai',
        total_products: 2,
        total_qty: 15,
        total_amount: '₹0.01',
        MRP_total: '₹136.82',
        on_hold_by: '-',
        confirmed_by: '-',
        status: 'On Hold',
    },
    {
        GRN_number: 'GR101001020',
        GRN_date_time: '20/09/2023 3:43:57 PM',
        invoice_date: '17-09-2023',
        invoice_number: 'IS101001007',
        vendor_name: 'BharatBhai',
        total_products: 1,
        total_qty: 7,
        total_amount: '₹441.3',
        MRP_total: '₹136.82',
        on_hold_by: '-',
        confirmed_by: '-',
        status: 'Invoiced',
    },
    {
        GRN_number: 'GR101001020',
        GRN_date_time: '20/09/2023 3:43:57 PM',
        invoice_date: '17-09-2023',
        invoice_number: 'IS101001098',
        vendor_name: 'BharatBhai',
        total_products: 2,
        total_qty: 45,
        total_amount: '₹93.49',
        MRP_total: '₹136.82',
        on_hold_by: '-',
        confirmed_by: '-',
        status: 'On Hold',
    },
    {
        GRN_number: 'GR101001020',
        GRN_date_time: '20/09/2023 3:43:57 PM',
        invoice_date: '16-09-2023',
        invoice_number: 'IS101001078',
        vendor_name: 'BharatBhai',
        total_products: 1,
        total_qty: 9,
        total_amount: '₹123.27',
        MRP_total: '₹136.82',
        on_hold_by: '-',
        confirmed_by: '-',
        status: 'Invoiced',
    },
    {
        GRN_number: 'GR101001020',
        GRN_date_time: '20/09/2023 3:43:57 PM',
        invoice_date: '16-09-2023',
        invoice_number: 'IS101001024',
        vendor_name: 'BharatBhai',
        total_products: 1,
        total_qty: 12,
        total_amount: '₹123.27',
        MRP_total: '₹136.82',
        on_hold_by: '-',
        confirmed_by: '-',
        status: 'Invoiced',
    },
    {
        GRN_number: 'GR101001020',
        GRN_date_time: '20/09/2023 3:43:57 PM',
        invoice_date: '16-09-2023',
        invoice_number: 'IS101001056',
        vendor_name: 'BharatBhai',
        total_products: 2,
        total_qty: 10,
        total_amount: '₹123.27',
        MRP_total: '₹136.82',
        on_hold_by: '-',
        confirmed_by: '-',
        status: 'On Hold',
    },
];

const purchaseinvoice = [
    {
        invoice_date: '20-09-2023',
        PI_no: 'PI101001015',
        invoice_no: 'IS101001034',
        GRN_no: 'GR101001020',
        vendor_name: 'BharatBhai',
        total_products: 1,
        total_qty: 2,
        total_amount: '₹123.27',
    },
    {

        invoice_date: '24-07-2023',
        PI_no: 'PI101001014',
        invoice_no: 'IS101001055',
        GRN_no: 'GR101001020',
        vendor_name: 'BharatBhai',
        total_products: 2,
        total_qty: 1,
        total_amount: '₹842.35',
    },
    {
        invoice_date: '19-07-2023',
        PI_no: 'PI101001015',
        invoice_no: 'IS101001043',
        GRN_no: 'GR101001020',
        vendor_name: 'BharatBhai',
        total_products: 1,
        total_qty: 6,
        total_amount: '₹127.68',
    },
    {
        invoice_date: '18-09-2023',
        PI_no: 'PI101001015',
        invoice_no: 'IS101001076',
        GRN_no: 'GR101001020',
        vendor_name: 'BharatBhai',
        total_products: 1,
        total_qty: 3,
        total_amount: '₹4480',
    },
    {
        invoice_date: '17-09-2023',
        PI_no: 'PI101001015',
        invoice_no: 'IS101001045',
        GRN_no: 'GR101001020',
        vendor_name: 'BharatBhai',
        total_products: 2,
        total_qty: 15,
        total_amount: '₹0.01',
    },
    {
        invoice_date: '17-09-2023',
        PI_no: 'PI101001015',
        invoice_no: 'IS101001007',
        GRN_no: 'GR101001020',
        vendor_name: 'BharatBhai',
        total_products: 1,
        total_qty: 7,
        total_amount: '₹441.3',
    },
    {
        invoice_date: '17-09-2023',
        PI_no: 'PI101001015',
        invoice_no: 'IS101001098',
        GRN_no: 'GR101001020',
        vendor_name: 'BharatBhai',
        total_products: 2,
        total_qty: 45,
        total_amount: '₹93.49',
    },
    {
        invoice_date: '16-09-2023',
        PI_no: 'PI101001015',
        invoice_no: 'IS101001078',
        GRN_no: 'GR101001020',
        vendor_name: 'BharatBhai',
        total_products: 1,
        total_qty: 9,
        total_amount: '₹123.27',
    },
    {
        invoice_date: '16-09-2023',
        PI_no: 'PI101001015',
        invoice_no: 'IS101001024',
        GRN_no: 'GR101001020',
        vendor_name: 'BharatBhai',
        total_products: 1,
        total_qty: 12,
        total_amount: '₹123.27',
    },
    {
        invoice_date: '16-09-2023',
        PI_no: 'PI101001015',
        invoice_no: 'IS101001056',
        GRN_no: 'GR101001020',
        vendor_name: 'BharatBhai',
        total_products: 2,
        total_qty: 10,
        total_amount: '₹123.27',
    },
];

const returninward = [
    {
        date_time: '22-07-2023 3:20 PM',
        transfer_from: 'Arun Riderboy',
        credit_note_no: '-',
        voucher_no: 'RI101001004',
        total_products: 3,
        total_billed_qty: 30,
        total_received_qty: 10,
        amount: '₹285.60',
        status: 'Draft',
    },
    {
        date_time: '22-07-2023 3:20 PM',
        transfer_from: 'Saurabh Bhatteja',
        credit_note_no: '-',
        voucher_no: 'RI101001004',
        total_products: 3,
        total_billed_qty: 30,
        total_received_qty: 10,
        amount: '₹285.60',
        status: 'Draft',
    },
    {
        date_time: '20-07-2023 3:20 PM',
        transfer_from: 'Vishal',
        credit_note_no: '-',
        voucher_no: 'RI101001004',
        total_products: 3,
        total_billed_qty: 30,
        total_received_qty: 10,
        amount: '₹285.60',
        status: 'Draft',
    },
    {
        date_time: '20-07-2023 3:20 PM',
        transfer_from: 'Vishal',
        credit_note_no: 'CN101001003',
        voucher_no: 'RI101001004',
        total_products: 3,
        total_billed_qty: 30,
        total_received_qty: 10,
        amount: '₹4480.60',
        status: 'Inward Completed',
    },
    {
        date_time: '18-07-2023 3:20 PM',
        transfer_from: '',
        credit_note_no: '-',
        voucher_no: 'RI101001004',
        total_products: 3,
        total_billed_qty: 30,
        total_received_qty: 10,
        amount: '₹285.60',
        status: 'Draft',
    },
    {
        date_time: '18-07-2023 3:20 PM',
        transfer_from: '',
        credit_note_no: '-',
        voucher_no: 'RI101001004',
        total_products: 3,
        total_billed_qty: 30,
        total_received_qty: 10,
        amount: '₹4480.60',
        status: 'Draft',
    },
    {
        date_time: '15-07-2023 3:20 PM',
        transfer_from: '',
        credit_note_no: 'CN101001003',
        voucher_no: 'RI101001004',
        total_products: 3,
        total_billed_qty: 30,
        total_received_qty: 10,
        amount: '₹285.60',
        status: 'Inward Completed',
    },
    {
        date_time: '15-07-2023 3:20 PM',
        transfer_from: '',
        credit_note_no: '-',
        voucher_no: 'RI101001004',
        total_products: 3,
        total_billed_qty: 30,
        total_received_qty: 10,
        amount: '₹4480.60',
        status: 'Draft',
    },
];

const creditnotes = [
    {
        date_time: '22-07-2023 3:20 PM',
        transfer_from: 'Arun Riderboy',
        credit_note_no: 'CN101001003',
        invoice_no: 'RI101001004',
        total_products: 3,
        total_qty: 30,
        amount: '₹285.60',
    },
    {
        date_time: '20-07-2023 3:20 PM',
        transfer_from: 'Saurabh Bhatteja',
        credit_note_no: 'CN101001023',
        invoice_no: 'RI101001065',
        total_products: 2,
        total_qty: 40,
        amount: '₹245.60',
    },
];

const bankmaster = [
    {
        account_type: 'BANK',
        account_name: 'banktest',
        account_number: '20484227961',
        bank_name: 'ICICI',
        balance: '₹(+) 0.00',
    },
    {
        account_type: 'BANK',
        account_name: 'hiren c',
        account_number: '20484365474',
        bank_name: 'HDFC',
        balance: '₹(+) 0.00',
    },
    {
        account_type: 'BANK',
        account_name: 'Harshil R',
        account_number: '204847684841',
        bank_name: 'UNION',
        balance: '₹(+) 0.00',
    },
    {
        account_type: 'BANK',
        account_name: 'Arth A',
        account_number: '20400990990',
        bank_name: 'SBI',
        balance: '₹(+) 0.00',
    },
    {
        account_type: 'BANK',
        account_name: 'Nishu A',
        account_number: '20480997812',
        bank_name: 'BOB',
        balance: '₹(+) 0.00',
    },
    {
        account_type: 'BANK',
        account_name: 'Deep J',
        account_number: '2048422344334',
        bank_name: 'BOI',
        balance: '₹(+) 0.00',
    },
];

const receiptdata = [
    {
        date: '21-07-2023',
        receipt_no: 'RT101001047',
        account_name: 'WMS BANK',
        type: 'Customer Payment',
        opposite_account: 'SHREE HARI MEDICAL',
        created_by: 'Jenil Kundaliya (21-07-2023 2:53 PM)',
        payment_mode: 'UPI',
        amount: '₹1520.06',
    },
    {
        date: '21-07-2023',
        receipt_no: 'RT101001060',
        account_name: 'WMS BANK',
        type: 'Customer Payment',
        opposite_account: 'CURE PHARMACY',
        created_by: 'Jenil Kundaliya (21-07-2023 2:53 PM)',
        payment_mode: 'UPI',
        amount: '₹63.84',
    },
    {
        date: '21-07-2023',
        receipt_no: 'RT101001030',
        account_name: 'WMS BANK',
        type: 'Customer Payment',
        opposite_account: 'SHREE HARI MEDICAL',
        created_by: 'Jenil Kundaliya (20-07-2023 2:53 PM)',
        payment_mode: 'Credit Card',
        amount: '₹2000',
    },
    {
        date: '20-07-2023',
        receipt_no: 'RT101001010',
        account_name: 'WMS BANK',
        type: 'Advance Payment',
        opposite_account: 'CURE PHARMACY',
        created_by: 'Saurav Khodal (20-07-2023 2:53 PM)',
        payment_mode: 'Debit Card',
        amount: '₹30',
    },
    {
        date: '20-07-2023',
        receipt_no: 'RT101001040',
        account_name: 'WMS BANK',
        type: 'Advance Payment',
        opposite_account: 'pankaj kumar pandya',
        created_by: 'Saurav Khodal (20-07-2023 2:53 PM)',
        payment_mode: 'Bank',
        amount: '₹15',
    },
    {
        date: '20-07-2023',
        receipt_no: 'RT101001050',
        account_name: 'WMS BANK',
        type: 'Advance Payment',
        opposite_account: 'SHREE HARI MEDICAL',
        created_by: 'Harshil Patel (19-07-2023 2:53 PM)',
        payment_mode: 'Credit Card',
        amount: '₹30',
    },
    {
        date: '19-07-2023',
        receipt_no: 'RT101001023',
        account_name: 'WMS BANK',
        type: 'Vendor Refund',
        opposite_account: 'CURE PHARMACY',
        created_by: 'Harshil Patel (19-07-2023 2:53 PM)',
        payment_mode: 'QR Code',
        amount: '₹134',
    },
    {
        date: '19-07-2023',
        receipt_no: 'RT101001009',
        account_name: 'WMS BANK',
        type: 'Vendor Refund',
        opposite_account: 'CURE PHARMACY',
        created_by: 'Hiren Patel (18-07-2023 2:53 PM)',
        payment_mode: 'QR Code',
        amount: '₹25',
    },
    {
        date: '19-07-2023',
        receipt_no: 'RT101001087',
        account_name: 'WMS BANK',
        type: 'Vendor Refund',
        opposite_account: 'pankaj kumar pandya',
        created_by: 'Hiren Patel (18-07-2023 2:53 PM)',
        payment_mode: 'Net Banking',
        amount: '₹20',
    },
    {
        date: '19-07-2023',
        receipt_no: 'RT101001345',
        account_name: 'WMS BANK',
        type: 'Vendor Refund',
        opposite_account: 'SHREE HARI MEDICAL',
        created_by: 'Saurav Khodal (18-07-2023 2:53 PM)',
        payment_mode: 'Net Banking',
        amount: '₹18',
    },
];

const payments = [
    {
        date: '21-07-2023',
        payment_no: 'PT101001000',
        type: 'Customer Payment',
        opposite_account: 'SHREE HARI MEDICAL',
        created_by: 'Jenil Kundaliya (21-07-2023 2:53 PM)',
        payment_mode: 'UPI',
        amount: '₹1520.06',
    },
    {
        date: '21-07-2023',
        payment_no: 'PT101001090',
        type: 'Customer Payment',
        opposite_account: 'CURE PHARMACY',
        created_by: 'Jenil Kundaliya (21-07-2023 2:53 PM)',
        payment_mode: 'UPI',
        amount: '₹63.84',
    },
    {
        date: '21-07-2023',
        payment_no: 'PT101001080',
        type: 'Customer Payment',
        opposite_account: 'SHREE HARI MEDICAL',
        created_by: 'Jenil Kundaliya (20-07-2023 2:53 PM)',
        payment_mode: 'Credit Card',
        amount: '₹2000',
    },
    {
        date: '20-07-2023',
        payment_no: 'PT101001060',
        type: 'Advance Payment',
        opposite_account: 'CURE PHARMACY',
        created_by: 'Saurav Khodal (20-07-2023 2:53 PM)',
        payment_mode: 'Debit Card',
        amount: '₹30',
    },
    {
        date: '20-07-2023',
        payment_no: 'PT101001050',
        type: 'Advance Payment',
        opposite_account: 'pankaj kumar pandya',
        created_by: 'Saurav Khodal (20-07-2023 2:53 PM)',
        payment_mode: 'Bank',
        amount: '₹15',
    },
    {
        date: '20-07-2023',
        payment_no: 'PT101001040',
        type: 'Advance Payment',
        opposite_account: 'SHREE HARI MEDICAL',
        created_by: 'Harshil Patel (19-07-2023 2:53 PM)',
        payment_mode: 'Credit Card',
        amount: '₹30',
    },
    {
        date: '19-07-2023',
        payment_no: 'PT101001030',
        type: 'Vendor Payment',
        opposite_account: 'CURE PHARMACY',
        created_by: 'Harshil Patel (19-07-2023 2:53 PM)',
        payment_mode: 'QR Code',
        amount: '₹134',
    },
    {
        date: '19-07-2023',
        payment_no: 'PT101001020',
        type: 'Vendor Payment',
        opposite_account: 'CURE PHARMACY',
        created_by: 'Hiren Patel (18-07-2023 2:53 PM)',
        payment_mode: 'QR Code',
        amount: '₹25',
    },
    {
        date: '19-07-2023',
        payment_no: 'PT101001010',
        type: 'Vendor Payment',
        opposite_account: 'pankaj kumar pandya',
        created_by: 'Hiren Patel (18-07-2023 2:53 PM)',
        payment_mode: 'Net Banking',
        amount: '₹20',
    },
    {
        date: '19-07-2023',
        payment_no: 'PT101001456',
        type: 'Vendor Payment',
        opposite_account: 'SHREE HARI MEDICAL',
        created_by: 'Saurav Khodal (18-07-2023 2:53 PM)',
        payment_mode: 'Net Banking',
        amount: '₹18',
    },
];

const usermanagement = [
    {
        full_name: 'Harshil',
        email: 'hatshil301099@gmail.com',
        role: 'SUPER_ADMIN',
        warehouse: 'HO',
        last_login: '1 M',
        status: ''
    },
    {
        full_name: 'Harsh',
        email: 'harsh.k@medkart.in',
        role: 'SUPERVISOR',
        warehouse: 'HO',
        last_login: '1 M',
        status: ''
    },
    {
        full_name: 'soni',
        email: 'soni@gmail.com',
        role: 'SUPER_ADMIN',
        warehouse: 'HO',
        last_login: '1 M',
        status: ''
    },
    {
        full_name: 'Savan',
        email: 'savan.d@medkart.in',
        role: 'SUPER_ADMIN',
        warehouse: 'HO',
        last_login: 'Unknown',
        status: ''
    },
    {
        full_name: 'saurabh',
        email: 'khodalsaurabh2309@gmail.com',
        role: 'SUPERVISOR',
        warehouse: 'HO',
        last_login: '1 M',
        status: 'Invited'
    },
    {
        full_name: 'Rajdip',
        email: 'rajdeephumbal27@gmail.com',
        role: 'SUPER_ADMIN',
        warehouse: 'HO',
        last_login: 'Unknown',
        status: ''
    },
    {
        full_name: 'Bhawna',
        email: 'bhawna.s@medkart.in',
        role: 'SUPERVISOR',
        warehouse: 'HO',
        last_login: '1 M',
        status: ''
    },
    {
        full_name: 'Yashpal',
        email: 'raj@medkart.in',
        role: 'SUPER_ADMIN',
        warehouse: 'HO',
        last_login: 'Unknown',
        status: 'Invited'
    },
    {
        full_name: 'Kishan',
        email: 'kishan.m1@medkart.in',
        role: 'SUPER_ADMIN',
        warehouse: 'HO',
        last_login: '3 D',
        status: ''
    },
    {
        full_name: 'Pratibha',
        email: 'pratibha.t@medkart.in',
        role: 'SUPERVISOR',
        warehouse: 'HO',
        last_login: '2 D',
        status: 'Invited'
    },
];

const importhistory = [
    {
        import_label: 'PURCHASE_ORDER_252',
        module: 'PURCHASE_ORDER',
        records_created: '0',
        records_updated: '0',
        records_errored: '0',
        imported_by: 'Hari (03-08-2023 5:43 PM)',
        status: 'Processed',
    },
    {
        import_label: 'MRPPTRRATIO_251',
        module: 'MRPPTRRATIO',
        records_created: '1',
        records_updated: '4',
        records_errored: '0',
        imported_by: 'Raj (24-07-2023 2:57 PM)',
        status: 'Validated',
    },
    {
        import_label: 'REALLOCATION_250',
        module: 'REALLOCATION',
        records_created: '0',
        records_updated: '0',
        records_errored: '0',
        imported_by: 'Pratibha (24-07-2023 2:56 PM)',
        status: 'Processing',
    },
    {
        import_label: 'REALLOCATION_249',
        module: 'REALLOCATION',
        records_created: '6',
        records_updated: '2',
        records_errored: '0',
        imported_by: 'Pratibha (24-07-2023 2:53 PM)',
        status: 'Processing',
    },
    {
        import_label: 'MRPPTRRATIO_248',
        module: 'MRPPTRRATIO',
        records_created: '0',
        records_updated: '0',
        records_errored: '0',
        imported_by: 'Raj (24-07-2023 2:52 PM)',
        status: 'Validated',
    },
    {
        import_label: 'MRPPTRRATIO_247',
        module: 'MRPPTRRATIO',
        records_created: '0',
        records_updated: '0',
        records_errored: '0',
        imported_by: 'Raj (24-07-2023 2:51 PM)',
        status: 'Initiated',
    },
    {
        import_label: 'MRPPTRRATIO_246',
        module: 'MRPPTRRATIO',
        records_created: '2',
        records_updated: '3',
        records_errored: '0',
        imported_by: 'Raj (24-07-2023 2:48 PM)',
        status: 'Pending',
    },
    {
        import_label: 'MRPPTRRATIO_245',
        module: 'MRPPTRRATIO',
        records_created: '0',
        records_updated: '0',
        records_errored: '0',
        imported_by: 'Raj (24-07-2023 1:31 PM)',
        status: 'Validating',
    },
    {
        import_label: 'MRPPTRRATIO_244',
        module: 'MRPPTRRATIO',
        records_created: '0',
        records_updated: '0',
        records_errored: '0',
        imported_by: 'Hari (03-08-2023 5:43 PM)',
        status: 'Validating',
    },
    {
        import_label: 'MRPPTRRATIO_243',
        module: 'MRPPTRRATIO',
        records_created: '5',
        records_updated: '5',
        records_errored: '0',
        imported_by: 'Hari (03-08-2023 5:43 PM)',
        status: 'Pending',
    },
];

const b2bpricingmaster = [
    {
        template_name: 'INRATENF',
        ethical: 'PTR - 5 %',
        generic: 'CTR + 9 %',
        generics: 'PTR + 9 %',
        ethical0: 'PTR + 0 %',
        ethical_special: 'CTR + 4 %',
        generic_l: 'CTR + 12 %',
        status: '',
    },
    {
        template_name: 'INRATEOTHERS',
        ethical: 'PTR - 5 %',
        generic: 'CTR + 7 %',
        generics: 'PTR + 7 %',
        ethical0: 'PTR + 0 %',
        ethical_special: 'CTR + 3 %',
        generic_l: 'CTR + 10 %',
        Status: '',
    },
    {
        template_name: 'INRATEAHM',
        ethical: 'PTR - 5 %',
        generic: 'CTR + 6 %',
        generics: 'PTR + 6 %',
        ethical0: 'PTR + 0 %',
        ethical_special: 'CTR + 3 %',
        generic_l: 'CTR + 9 %',
        Status: '',
    },
    {
        template_name: 'INRATEOTHERS',
        ethical: 'PTR - 0 %',
        generic: 'CTR + 0 %',
        generics: 'PTR + 0 %',
        ethical0: 'PTR + 0 %',
        ethical_special: 'CTR + 0 %',
        generic_l: 'CTR + 0 %',
        Status: '',
    },
    {
        template_name: 'COCO @ Cost',
        ethical: 'PTR - 5 %',
        generic: 'CTR + 9 %',
        generics: 'PTR + 9 %',
        ethical0: 'PTR + 0 %',
        ethical_special: 'CTR + 4 %',
        generic_l: 'CTR + 12 %',
        Status: '',
    },
];

const exporthistorycolumn = [
    {
        fieldKey: 'import_label',
        label: "Import Label",
        tdClass: "ps-4",
        valueTdClass: "ps-4",
    },
    {
        fieldKey: 'module',
        label: "Module",
        tdClass: "",
        valueTdClass: "",
    },
    {
        fieldKey: 'created_by',
        label: "Created By",
        tdClass: "",
        valueTdClass: "text-primary",
    },
    {
        fieldKey: 'updated_at',
        label: "Updated At",
        tdClass: "",
        valueTdClass: "",
    },
    {
        fieldKey: 'completed_at',
        label: "Completed At",
        tdClass: "",
        valueTdClass: "",
    },
    {
        fieldKey: 'status',
        label: "Status",
        tdClass: "",
        valueTdClass: "",
    },
    {
        fieldKey: '',
        label: "",
        tdClass: "",
        valueTdClass: "",
    },
];


const exporthistoryTData = [
    {
        import_label: 'gfgfh',
        module: 'gfd',
        created_by: 'gfd',
        updated_at: 'dg',
        completed_at: 'iu',
        status: 'bnvc',
    },
    {
        created_by: '13',
        updated_at: '13',
        completed_at: '45',
        status: 'None',
    },

];

const testdata = [
    {
        product_code: 67677,
        wondersoft_code: 23453,
        product_name: 'FDSON MP D3 TAB 1X10',
        manufacturer: 'WELLNESS REMEDIES PVT LTD',
        combination: '	LEVOCETIRIZINE 10 MG',
        status: 'Published',
    },
    {
        product_code: 34562,
        wondersoft_code: 78783,
        product_name: '	1 AL MAX TAB 1X10',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'LEVOCETIRIZINE 5 MG+MONTELUKAST 10 MG',
        status: 'Published',
    },
    {
        product_code: 98989,
        wondersoft_code: 34783,
        product_name: '	1 AL SYP 30ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'LEVOCETIRIZINE 2.5 MG /5ML',
        status: 'Published',
    },
    {
        product_code: 98687,
        wondersoft_code: 34573,
        product_name: '	1 AL TAB 1X10',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'LEVOCETIRIZINE 5 MG',
        status: 'Unpublished',
    },
    {
        product_code: 67500,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Published',
    },
    {
        product_code: 67400,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Unpublished',
    },
    {
        product_code: 48983,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Published',
    },
    {
        product_code: 18992,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Unpublished',
    },
    {
        product_code: 24531,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Published',
    },
    {
        product_code: 7986,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Published',
    },
    {
        product_code: 69345,
        wondersoft_code: 23453,
        product_name: 'FDSON MP D3 TAB 1X10',
        manufacturer: 'WELLNESS REMEDIES PVT LTD',
        combination: '	LEVOCETIRIZINE 10 MG',
        status: 'Published',
    },
    {
        product_code: 37653,
        wondersoft_code: 78783,
        product_name: '	1 AL MAX TAB 1X10',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'LEVOCETIRIZINE 5 MG+MONTELUKAST 10 MG',
        status: 'Published',
    },
    {
        product_code: 87697,
        wondersoft_code: 34783,
        product_name: '	1 AL SYP 30ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'LEVOCETIRIZINE 2.5 MG /5ML',
        status: 'Published',
    },
    {
        product_code: 80909,
        wondersoft_code: 34573,
        product_name: '	1 AL TAB 1X10',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'LEVOCETIRIZINE 5 MG',
        status: 'Unpublished',
    },
    {
        product_code: 90403,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Published',
    },
    {
        product_code: 80907,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Unpublished',
    },
    {
        product_code: 20564,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Published',
    },
    {
        product_code: 60403,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Unpublished',
    }, {
        product_code: 87768,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Published',
    },
    {
        product_code: 57667,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Published',
    },
    {
        product_code: 88733,
        wondersoft_code: 23453,
        product_name: 'FDSON MP D3 TAB 1X10',
        manufacturer: 'WELLNESS REMEDIES PVT LTD',
        combination: '	LEVOCETIRIZINE 10 MG',
        status: 'Published',
    },
    {
        product_code: 34562,
        wondersoft_code: 78783,
        product_name: '	1 AL MAX TAB 1X10',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'LEVOCETIRIZINE 5 MG+MONTELUKAST 10 MG',
        status: 'Published',
    },
    {
        product_code: 98989,
        wondersoft_code: 34783,
        product_name: '	1 AL SYP 30ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'LEVOCETIRIZINE 2.5 MG /5ML',
        status: 'Published',
    },
    {
        product_code: 98687,
        wondersoft_code: 34573,
        product_name: '	1 AL TAB 1X10',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'LEVOCETIRIZINE 5 MG',
        status: 'Unpublished',
    },
    {
        product_code: 8982,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Published',
    },
    {
        product_code: 45376,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Unpublished',
    },
    {
        product_code: 767632,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Published',
    },
    {
        product_code: 89732,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Unpublished',
    },
    {
        product_code: 434312,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Published',
    },
    {
        product_code: 23423,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Published',
    }, {
        product_code: 65456,
        wondersoft_code: 23453,
        product_name: 'FDSON MP D3 TAB 1X10',
        manufacturer: 'WELLNESS REMEDIES PVT LTD',
        combination: '	LEVOCETIRIZINE 10 MG',
        status: 'Published',
    },
    {
        product_code: 34562,
        wondersoft_code: 78783,
        product_name: '	1 AL MAX TAB 1X10',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'LEVOCETIRIZINE 5 MG+MONTELUKAST 10 MG',
        status: 'Published',
    },
    {
        product_code: 98989,
        wondersoft_code: 34783,
        product_name: '	1 AL SYP 30ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'LEVOCETIRIZINE 2.5 MG /5ML',
        status: 'Published',
    },
    {
        product_code: 98687,
        wondersoft_code: 34573,
        product_name: '	1 AL TAB 1X10',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'LEVOCETIRIZINE 5 MG',
        status: 'Unpublished',
    },
    {
        product_code: 78973,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Published',
    },
    {
        product_code: 88873,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Unpublished',
    },
    {
        product_code: 99999,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Published',
    },
    {
        product_code: 67576,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Unpublished',
    },
    {
        product_code: 33244,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Published',
    },
    {
        product_code: 42344,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Published',
    }, {
        product_code: 9887,
        wondersoft_code: 23453,
        product_name: 'FDSON MP D3 TAB 1X10',
        manufacturer: 'WELLNESS REMEDIES PVT LTD',
        combination: '	LEVOCETIRIZINE 10 MG',
        status: 'Published',
    },
    {
        product_code: 34562,
        wondersoft_code: 78783,
        product_name: '	1 AL MAX TAB 1X10',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'LEVOCETIRIZINE 5 MG+MONTELUKAST 10 MG',
        status: 'Published',
    },
    {
        product_code: 98989,
        wondersoft_code: 34783,
        product_name: '	1 AL SYP 30ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'LEVOCETIRIZINE 2.5 MG /5ML',
        status: 'Published',
    },
    {
        product_code: 98687,
        wondersoft_code: 34573,
        product_name: '	1 AL TAB 1X10',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'LEVOCETIRIZINE 5 MG',
        status: 'Unpublished',
    },
    {
        product_code: 87689,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Published',
    },
    {
        product_code: 44444,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Unpublished',
    },
    {
        product_code: 67666,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Published',
    },
    {
        product_code: 10555,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Unpublished',
    },
    {
        product_code: 20333,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Published',
    },
    {
        product_code: 10333,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Published',
    }, {
        product_code: 69898,
        wondersoft_code: 23453,
        product_name: 'FDSON MP D3 TAB 1X10',
        manufacturer: 'WELLNESS REMEDIES PVT LTD',
        combination: '	LEVOCETIRIZINE 10 MG',
        status: 'Published',
    },
    {
        product_code: 34562,
        wondersoft_code: 78783,
        product_name: '	1 AL MAX TAB 1X10',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'LEVOCETIRIZINE 5 MG+MONTELUKAST 10 MG',
        status: 'Published',
    },
    {
        product_code: 98989,
        wondersoft_code: 34783,
        product_name: '	1 AL SYP 30ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'LEVOCETIRIZINE 2.5 MG /5ML',
        status: 'Published',
    },
    {
        product_code: 98687,
        wondersoft_code: 34573,
        product_name: '	1 AL TAB 1X10',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'LEVOCETIRIZINE 5 MG',
        status: 'Unpublished',
    },
    {
        product_code: 11111,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Published',
    },
    {
        product_code: 99999,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Unpublished',
    },
    {
        product_code: 55555,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Published',
    },

];

const testdatacolumn = [
    {
        fieldKey: 'product_code',
        label: 'Product Code',
        tdClass: 'ps-3',
        valueTdClass: 'ps-3',
        enableCheck:true,
        customfield: (row) => {
            return (
                <div className="d-flex">
                    <input className="form-check-input me-3 g-0" type="checkbox" value=""></input>                                       
                    {row.label && <p className="mb-0">{row.label}</p>}
                    {row.product_code && <p className="mb-0">{row.product_code}</p>}
                </div>
            );
        },
    },
    {
        fieldKey: 'wondersoft_code',
        label: 'Wondersoft Code',
    },
    {
        fieldKey: 'product_name',
        label: 'Product Name',
    },
    {
        fieldKey: 'manufacturer',
        label: 'Manufacturer',
    },
    {
        fieldKey: 'combination',
        label: 'Combination',
    },
    {
        fieldKey: 'status',
        label: 'Status',
        customfield: (row) => {
            return (
                row === "Published" ?
                    <span className="d-flex align-items-center justify-content-center rounded-pill px-2" style={{ backgroundColor: 'rgb(186, 240, 218)', width: 'fit-content' }}>
                        <span className="p-1 rounded-circle me-1 " style={{ backgroundColor: 'rgb(0, 127, 95)' }}></span>
                        <span>{row}</span>
                    </span> : row === "Unpublished" ?
                        <span className="d-flex align-items-center justify-content-center rounded-pill px-2" style={{ backgroundColor: 'rgb(255, 219, 185)', width: 'fit-content' }}>
                            <span className="p-1 rounded-circle me-1 " style={{ backgroundColor: 'rgb(228, 130, 75)' }}></span>
                            <span>{row}</span>
                        </span> : ''
            );
        }
    },
    {

        customfield: (row) => {
            return (
                <div className='d-flex justify-content-end me-2'>                    
                    <button className='p-0 border-0 rounded-1' onClick={() => console.log("rowdata", row)}><img src='delete_icon.svg' alt='download_icon' /></button>
                </div>
            )
        }
    },
    {

        customfield: (row) => {
            return (
                <div className='d-flex justify-content-end me-2'>
                    <button className='p-0 border-0 rounded-1 me-2' onClick={() => console.log("rowdata", row)}><img src='Edit-button.svg' alt='download_icon' /></button>
                    <button className='p-0 border-0 rounded-1' onClick={() => console.log("rowdata", row)}><img src='report_download_icon.svg' alt='download_icon' /></button>
                </div>
            )
        }
    }
];

export default {
    unpublished, locationmaster, minmaxmaster, moleculemaster, manufacturemaster, vendormaster, productchannelmapping,
    b2cPricingMaster, storeMaster, warehousemaster, MrpPtrData, stockadjustment, stockrearrange, reallocation, transferout,
    internalsales, b2csales, checkingtracker, grn, purchaseinvoice, returninward, creditnotes, bankmaster, receiptdata, payments,
    usermanagement, importhistory, b2bpricingmaster, exporthistorycolumn, exporthistoryTData, testdata, testdatacolumn
};