const unpublished = [
    {
        product_code: 67677,
        wondersoft_code: 23453,
        product_name: 'FDSON MP D3 TAB 1X10',
        manufacturer: 'WELLNESS REMEDIES PVT LTD',
        combination: '	LEVOCETIRIZINE 10 MG',
        status: 'Published',
    },
    {
        product_code: 34562,
        wondersoft_code: 78783,
        product_name: '	1 AL MAX TAB 1X10',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'LEVOCETIRIZINE 5 MG+MONTELUKAST 10 MG',
        status: 'Published',
    },
    {
        product_code: 98989,
        wondersoft_code: 34783,
        product_name: '	1 AL SYP 30ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'LEVOCETIRIZINE 2.5 MG /5ML',
        status: 'Published',
    },
    {
        product_code: 98687,
        wondersoft_code: 34573,
        product_name: '	1 AL TAB 1X10',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'LEVOCETIRIZINE 5 MG',
        status: 'Unpublished',
    },
    {
        product_code: 67487,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Published',
    },
    {
        product_code: 67487,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Unpublished',
    },
    {
        product_code: 67487,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Published',
    },
    {
        product_code: 67487,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Unpublished',
    },
    {
        product_code: 67487,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Published',
    },
    {
        product_code: 67487,
        wondersoft_code: 34245,
        product_name: '	1 AL TOTAL SYP 60ML',
        manufacturer: 'F D C INDIA LIMITED',
        combination: 'AMBROXOL 60 MG+LEVOCETIRIZINE 5 ',
        status: 'Published',
    }
];

const locationmaster = [
    {
        product_code: 67677,
        wondersoft_code: 23453,
        product_name: 'FDSON MP D3 TAB 1X10',
        warehouse_code: 'HO(1)',
        section: 'A (FWD)',
        lane: 2, 
        rack: 'P',
        shelf: 2,
        box: 16,
    },
    {
        product_code: 67677,
        wondersoft_code: 23453,
        product_name: 'OVACARE FORTE KIT TAB 1X12',
        warehouse_code: 'HO(1)',
        section: 'A (FWD)',
        lane: 1, 
        rack: 'A',
        shelf: 3,
        box: 4,
    },
    {
        product_code: 67677,
        wondersoft_code: 23453,
        product_name: 'ALL 9 TAB 1X15',
        warehouse_code: 'HO(1)',
        section: 'A (FWD)',
        lane: 3, 
        rack: 'G',
        shelf: 1,
        box: 25,
    },
    {
        product_code: 67677,
        wondersoft_code: 23453,
        product_name: 'XSTAN 40MG TAB 1X15',
        warehouse_code: 'HO(1)',
        section: 'A (FWD)',
        lane: 4, 
        rack: 'F',
        shelf: 5,
        box: 10,
    },
    {
        product_code: 67677,
        wondersoft_code: 23453,
        product_name: 'ZORYL 0.5MG TAB 1X15',
        warehouse_code: 'HO(1)',
        section: 'A (FWD)',
        lane: 2, 
        rack: 'R',
        shelf: 3,
        box: 5,
    },
    {
        product_code: 67677,
        wondersoft_code: 23453,
        product_name: 'OPGLIM M 1MG TAB 1X15',
        warehouse_code: 'HO(1)',
        section: 'A (FWD)',
        lane: 5, 
        rack: 'P',
        shelf: 3,
        box: 9,
    },
    {
        product_code: 67677,
        wondersoft_code: 23453,
        product_name: 'NICARDIA XL 60MG TAB 1X15',
        warehouse_code: 'HO(1)',
        section: 'A (FWD)',
        lane: 1, 
        rack: 'D',
        shelf: 2,
        box: 6,
    },
    {
        product_code: 67677,
        wondersoft_code: 23453,
        product_name: 'GLIMER 1MG TAB 1X15',
        warehouse_code: 'HO(1)',
        section: 'A (FWD)',
        lane: 2, 
        rack: 'F',
        shelf: 2,
        box: 12,
    },
    {
        product_code: 67677,
        wondersoft_code: 23453,
        product_name: 'AMLONG TL 40MG TAB 1X10',
        warehouse_code: 'HO(1)',
        section: 'A (FWD)',
        lane: 4, 
        rack: 'B',
        shelf: 5,
        box: 4,
    },
    {
        product_code: 67677,
        wondersoft_code: 23453,
        product_name: 'MET XL AM 25/5MG TAB 1X20',
        warehouse_code: 'HO(1)',
        section: 'A (FWD)',
        lane: 5, 
        rack: 'H',
        shelf: 2,
        box: 15,
    },
];

const minmaxmaster = [
    {
        product_code: 67677,
        wondersoft_code: 3080,
        product_name: 'FDSON MP D3 TAB 1X10',
        warehouse: 'HO',
        min_value: 2,
        max_value: 20, 
        total_stock: 25,
        available: 25,
        reserved: 0,
        on_hold: 0,
    },
    {
        product_code: 68763,
        wondersoft_code: 3280,
        product_name: 'FDSON MP D3 TAB 1X10',
        warehouse: 'HO',
        min_value: 5,
        max_value: 40, 
        total_stock: 22,
        available: 22,
        reserved: 0,
        on_hold: 0,
    },
    {
        product_code: 67893,
        wondersoft_code: 3345,
        product_name: 'FDSON MP D3 TAB 1X10',
        warehouse: 'HO',
        min_value: 4,
        max_value: 215, 
        total_stock: 30,
        available: 30,
        reserved: 0,
        on_hold: 0,
    },
    {
        product_code: 69087,
        wondersoft_code: 3480,
        product_name: 'FDSON MP D3 TAB 1X10',
        warehouse: 'HO',
        min_value: 1,
        max_value: 10, 
        total_stock: 10,
        available: 10,
        reserved: 0,
        on_hold: 0,
    }, 
    {
        product_code: 67845,
        wondersoft_code: 3345,
        product_name: 'FDSON MP D3 TAB 1X10',
        warehouse: 'HO',
        min_value: 0,
        max_value: 5, 
        total_stock: 45,
        available: 45,
        reserved: 0,
        on_hold: 0,
    },
    {
        product_code: 65654,
        wondersoft_code: 2344,
        product_name: 'FDSON MP D3 TAB 1X10',
        warehouse: 'HO',
        min_value: 0,
        max_value: 2, 
        total_stock: 36,
        available: 36,
        reserved: 0,
        on_hold: 0,
    }, 
    {
        product_code: 60980,
        wondersoft_code: 3786,
        product_name: 'FDSON MP D3 TAB 1X10',
        warehouse: 'HO',
        min_value: 3,
        max_value: 30, 
        total_stock: 50,
        available: 50,
        reserved: 0,
        on_hold: 0,
    }, 
    {
        product_code: 62341,
        wondersoft_code: 3654,
        product_name: 'FDSON MP D3 TAB 1X10',
        warehouse: 'HO',
        min_value: 2,
        max_value: 8, 
        total_stock: 18,
        available: 18,
        reserved: 0,
        on_hold: 0,
    },
    {
        product_code: 67987,
        wondersoft_code: 3080,
        product_name: 'FDSON MP D3 TAB 1X10',
        warehouse: 'HO',
        min_value: 2,
        max_value: 20, 
        total_stock: 56,
        available: 56,
        reserved: 0,
        on_hold: 0,
    },
    {
        product_code: 67677,
        wondersoft_code: 3080,
        product_name: 'FDSON MP D3 TAB 1X10',
        warehouse: 'HO',
        min_value: 2,
        max_value: 20, 
        total_stock: 25,
        available: 25,
        reserved: 0,
        on_hold: 0,
    },                                 
];

const moleculemaster = [
    {
        molecule_name:'PIRFENIDONE 600 MG',
        is_refrigerated:'Yes',
        scheduled_type_code:'Schedule',
        ChronicAcute:'Acute',
        status:'Published',
    },
    {
        molecule_name:'METOPROLOL SUCCINATE 12.5 MG SUSTAINED REL',
        is_refrigerated:'No',
        scheduled_type_code:'Schedule',
        ChronicAcute:'Acute',
        status:'Published',
    },
    {
        molecule_name:'FLUVOXAMINE 100 MG CONTROLLED RELEASE',
        is_refrigerated:'No',
        scheduled_type_code:'Schedule',
        ChronicAcute:'Acute',
        status:'Published',
    },
    {
        molecule_name:'FLUVOXAMINE 100 MG CONTROLLED RELEASE',
        is_refrigerated:'No',
        scheduled_type_code:'Schedule',
        ChronicAcute:'Acute',
        status:'Published',
    },
    {
        molecule_name:'PARACETAMOL/ACETAMINOPHEN 650 MG SUSTAINED RELEASE',
        is_refrigerated:'No',
        scheduled_type_code:'Non Schedule',
        ChronicAcute:'Acute',
        status:'Published',
    },
    {
        molecule_name:'VILDAGLIPTIN 50 MG SUSTAINED RELEASE',
        is_refrigerated:'No',
        scheduled_type_code:'Non Schedule',
        ChronicAcute:'Chronic',
        status:'Published',
    },
    {
        molecule_name:'DOMPERIDONE 30 MG SUSTAINED RELEASE',
        is_refrigerated:'No',
        scheduled_type_code:'Schedule',
        ChronicAcute:'Acute',
        status:'Published',
    },
    {
        molecule_name:'NITROFURANTOIN 100 MG SUSTAINED RELEASE',
        is_refrigerated:'No',
        scheduled_type_code:'Non Schedule',
        ChronicAcute:'Acute',
        status:'Published',
    },
    {
        molecule_name:'PHENYTOIN 300 MG SUSTAINED RELEASE',
        is_refrigerated:'No',
        scheduled_type_code:'Schedule',
        ChronicAcute:'Chronic',
        status:'Published',
    },
    {
        molecule_name:'DOXOFYLLINE 650 MG SUSTAINED RELEASE',
        is_refrigerated:'No',
        scheduled_type_code:'Schedule',
        ChronicAcute:'Chronic',
        status:'Published',
    },    
];

const manufacturemaster = [
    {
        manufacturer_name:'DEEPP',
        created_by: 'System (19-06-2023 2:42 PM)',
        updated_by: 'WMS (14-07-2023 11:21 AM)',        	
        status: 'Draft'
    },
    {
        manufacturer_name:'A. MENARINI INDIA PRIVATE LIMITED',
        created_by: 'System (19-06-2023 2:42 PM)',
        updated_by: 'WMS (14-07-2023 11:21 AM)',        	
        status: 'Draft'
    },
    {
        manufacturer_name:'INNOVCARE LIFESCIENCES PRIVATE LIMITED',
        created_by: 'System (19-06-2023 2:42 PM)',
        updated_by: '(-)',        	
        status: 'Published'
    },
    {
        manufacturer_name:'SWADESH LIFE SCIENCE',
        created_by: 'System (19-06-2023 2:42 PM)',
        updated_by: '(-)',        	
        status: 'Published'
    },
    {
        manufacturer_name:'INCY HEALTHCARE PVT LTD',
        created_by: 'System (19-06-2023 2:42 PM)',
        updated_by: '(-)',        	
        status: 'Published'
    },
    {
        manufacturer_name:'MEDIMARCK BIOTECH PVT LTD',
        created_by: 'System (19-06-2023 2:42 PM)',
        updated_by: '(-)',        	
        status: 'Published'
    },
    {
        manufacturer_name:'MASCOT HEALTH SERIES PVT LTD',
        created_by: 'System (19-06-2023 2:42 PM)',
        updated_by: '(-)',        	
        status: 'Published'
    },
    {
        manufacturer_name:'ADONIS LABORATORIES PVT LTD',
        created_by: 'System (19-06-2023 2:42 PM)',
        updated_by: '(-)',        	
        status: 'Published'
    },
    {
        manufacturer_name:'BEIERSDORF INDIA LTD',
        created_by: 'System (19-06-2023 2:42 PM)',
        updated_by: '(-)',        	
        status: 'Published'
    },
    {
        manufacturer_name:'INVASION PHARMACEUTICALS PVT LTD',
        created_by: 'System (19-06-2023 2:42 PM)',
        updated_by: '(-)',        	
        status: 'Published'
    },
];

const vendormaster = [
    {
        vendor_name:'vendor check',
        contact_name:'-',
        contact_mobile: 9876543210,
        contact_email:'test@test.com',
        status:'Draft',
    },
    {
        vendor_name:'sample vendor data',
        contact_name:'-',
        contact_mobile: 9876543210,
        contact_email:'test@test.com',
        status:'Draft',
    },
    {
        vendor_name:'SHREE',
        contact_name:'Deep',
        contact_mobile: 9876543210,
        contact_email:'sample@testmail.com',
        status:'Published',
    },
    {
        vendor_name:'HARDIK DISTRIBUTORS',
        contact_name:'HARDIK DISTRIBUTORS',
        contact_mobile: 9876543210,
        contact_email:'sample@testmail.com',
        status:'Published',
    },
    {
        vendor_name:'TO BE deL',
        contact_name:'K B SHAH AND',
        contact_mobile: 9876543210,
        contact_email:'sample@testmail.com',
        status:'Published',
    },
    {
        vendor_name:'DHRUVI PHARMA PVT LTD',
        contact_name:'DHRUVI PHARMA PVT LTD',
        contact_mobile: 9876543210,
        contact_email:'sample@testmail.com',
        status:'Published',
    },
    {
        vendor_name:'ATHARVA BIO PRODUCTS',
        contact_name:'ATHARVA BIO PRODUCTS',
        contact_mobile: 9876543210,
        contact_email:'sample@testmail.com',
        status:'Published',
    },
    {
        vendor_name:'ZYMO BEAUTY SCIENCE PRIVATE LIMITED',
        contact_name:'ZYMO BEAUTY SCIENCE PRIVATE LIMITED',
        contact_mobile: 9876543210,
        contact_email:'sample@testmail.com',
        status:'Published',
    },
    {
        vendor_name:'DAYNACARE LIFESCIENCE',
        contact_name:'DAYNACARE LIFESCIENCE',
        contact_mobile: 9876543210,
        contact_email:'sample@testmail.com',
        status:'Published',
    },
    {
        vendor_name:'SUPAL PHARMA',
        contact_name:'SUPAL PHARMA',
        contact_mobile: 9876543210,
        contact_email:'sample@testmail.com',
        status:'Published',
    },
];

const productchannelmapping = [
    {
        product_code: 56739,
        wondersoft_code: 12342,
        product_name: 'GLICDUO XR 60/500MG TAB 1X10',
        vendor_name: '-',
        product_channel: 'PHARMA_RACK'
    },
    {
        product_code: 56244,
        wondersoft_code: 18743,
        product_name: 'SITASON 50MG TAB 1X10',
        vendor_name: '-',
        product_channel: 'UNISON'
    },
    {
        product_code: 56241,
        wondersoft_code: 12342,
        product_name: 'NULONG MT 25MG TAB 1X10',
        vendor_name: '-',
        product_channel: 'PHARMA_RACK'
    },
    {
        product_code: 56745,
        wondersoft_code: 18777,
        product_name: 'BITATEL M 3D 12.5/25/40MG TAB 1X10',
        vendor_name: '-',
        product_channel: 'PHARMA_RACK'
    },
    {
        product_code: 56876,
        wondersoft_code: 18465,
        product_name: 'M SOLVIN TAB 1X10',
        vendor_name: '-',
        product_channel: 'PHARMA_RACK'
    },
    {
        product_code: 56765,
        wondersoft_code: 18456,
        product_name: 'NEFVIT PLUS TAB 1X10',
        vendor_name: '-',
        product_channel: 'PHARMA_RACK'
    },
    {
        product_code: 56443,
        wondersoft_code: 17674,
        product_name: 'RABIFAST DSR CAP 1X15',
        vendor_name: '-',
        product_channel: 'PHARMA_RACK'
    },
    {
        product_code: 56739,
        wondersoft_code: 12442,
        product_name: 'NEUROKEM OD 75MG TAB 1X10',
        vendor_name: '-',
        product_channel: 'PHARMA_RACK'
    },
    {
        product_code: 56744,
        wondersoft_code: 14874,
        product_name: 'MORISONS SILICON NIPPLE ( MEDIUM )',
        vendor_name: '-',
        product_channel: 'OTHER'
    },
    {
        product_code: 56743,
        wondersoft_code: 17874,
        product_name: 'MORISONS POLY FEDER 125ML',
        vendor_name: '-',
        product_channel: 'OTHER'
    },    
];

const b2cPricingMaster = [
    {        
        category_name: 'Disc 30 Perc',
        discount: '30%',
    },
    {        
        category_name: 'Launch Category',
        discount: '30%',
    },
    {        
        category_name: 'Disc 25 Perc',
        discount: '25%',
    },
    {        
        category_name: 'Disc 20 Perc',
        discount: '20%',
    },
    {        
        category_name: 'Disc 15 Perc',
        discount: '15%',
    },
    {        
        category_name: 'Disc 10 Perc',
        discount: '10%',
    },
    {        
        category_name: 'Disc 5 Perc',
        discount: '5%',
    },
    {        
        category_name: 'Disc 0 Perc',
        discount: '0%',
    },
    {        
        category_name: 'Disc 40 Perc',
        discount: '40%',
    },
    {        
        category_name: 'Disc 35 Perc',
        discount: '35%',
    },
];

const storeMaster = [
    {
        wondersoft_store_ID:23,
        store_name: 'PURAV & ASSOCIATES',
        city: 'VADODARA',
        type: 'FOFO',
        status: 'Active',
    },
    {
        wondersoft_store_ID: 20,
        store_name: 'AKSHAR PHARMACY',
        city: 'AHMEDABAD',
        type: 'FOFO',
        status: 'Active',
    },
    {
        wondersoft_store_ID: 18,
        store_name: 'B&G ENTERPRISE',
        city: 'VADODARA',
        type: 'FOFO',
        status: 'Inactive',
    },
    {
        wondersoft_store_ID: 21,
        store_name: 'BK ENTERPRISE',
        city: 'VADODARA',
        type: 'FOFO',
        status: 'Active',
    },
    {
        wondersoft_store_ID: 40,
        store_name: 'FOSTEROOH ENTERPRISES LLP',
        city: 'AHMEDABAD',
        type: 'FOFO',
        status: 'Active',
    },
    {
        wondersoft_store_ID: 2,
        store_name: 'K AND T ASSOCIATE',
        city: 'VADODARA',
        type: 'FOFO',
        status: 'Inactive',
    },
    {
        wondersoft_store_ID: 30,
        store_name: 'MEDONE PHARMACY',
        city: 'AHMEDABAD',
        type: 'FOFO',
        status: 'Active',
    },
    {
        wondersoft_store_ID: 12,
        store_name: 'SHREE HARI MEDICAL',
        city: 'VADODARA',
        type: 'FOFO',
        status: 'Active',
    },
    {
        wondersoft_store_ID: 9,
        store_name: 'SANJIVANI MEDICAL',
        city: 'VADODARA',
        type: 'FOFO',
        status: 'Inactive',
    },
    {
        wondersoft_store_ID: 5,
        store_name: 'SANJIVANI PHARMACY',
        city: 'VADODARA',
        type: 'FOFO',
        status: 'Active',
    },
];

const warehousemaster= [
    {
        warehouse_code: 1,
        warehouse_name: 'HO',
        city: 'Ahmedabad',
        type: 'Owned',
        status: 'Active'
    }
];

const MrpPtrData = [
    {
        product_code:56436,
        wonderSoft_code: 3763,
        product_name: 'FEBIRED TAB 1X15',
        MRP: '₹117',
        mRP_PTR_ratio: 0.80000,
    },
    {
        product_code:87659,
        wonderSoft_code: 7845,
        product_name: 'NS INJ 1000ML',
        MRP: '₹23',
        mRP_PTR_ratio: 0.0256,
    },
    {
        product_code:54837,
        wonderSoft_code: 4763,
        product_name: 'OMILCAL SYP 200ML',
        MRP: '₹2',
        mRP_PTR_ratio: 0.4582,
    },
    {
        product_code:89734,
        wonderSoft_code: 6763,
        product_name: 'LUMIGAN 0.01% DROPS 3ML',
        MRP: '₹121',
        mRP_PTR_ratio: 0.54285,
    },
    {
        product_code:50987,
        wonderSoft_code:9898,
        product_name: 'THYRONORM 75MCG TAB 1X120',
        MRP: '₹5',
        mRP_PTR_ratio: 0.5438,
    },
    {
        product_code:5635,
        wonderSoft_code: 1263,
        product_name: 'AMODEP AT TAB 1X15',
        MRP: '₹10',
        mRP_PTR_ratio: 0.53553,
    },
    {
        product_code:12436,
        wonderSoft_code: 3963,
        product_name: 'FLAMINGO TENNIS ELBOW SUPPORT',
        MRP: '₹90',
        mRP_PTR_ratio: 0.5655,
    },
    {
        product_code:90436,
        wonderSoft_code: 3778,
        product_name: 'DAFLON 1000MG TAB 1X18',
        MRP: '₹121',
        mRP_PTR_ratio: 0.8946,
    },
    {
        product_code:12336,
        wonderSoft_code: 8963,
        product_name: 'ONABET SD SOLUTION 15ML',
        MRP: '₹100',
        mRP_PTR_ratio: 0.248841,
    },
    {
        product_code:76436,
        wonderSoft_code: 3908,
        product_name: 'FEBIRED TAB 1X15',
        MRP: '₹1',
        mRP_PTR_ratio: 0.8344,
    },
];

const stockadjustment = [
    {
        adj_no: 'SA101001009',
        date: '18-07-2023',
        type: 'Stock Adjustment',
        total_items: '2',
        total_adjusted_qty: '102',
        created_by: 'Raj Busa',
        approved_by_rejected_by: 'Jenil Kundaliya (20-07-2023 6:25 PM)',
        status: 'Approved',
    },
    {
        adj_no: 'SA101001008',
        date: '18-07-2023',
        type: 'Stock Adjustment',
        total_items: 3,
        total_adjusted_qty: 100,
        created_by: 'Raj Busa',
        approved_by_rejected_by: 'Jenil Kundaliya (20-07-2023 6:25 PM)',
        status: 'Draft',
    },
    {
        adj_no: 'SA101001007',
        date: '18-07-2023',
        type: 'Stock Adjustment',
        total_items: 3,
        total_adjusted_qty: 300,
        created_by: 'Raj Busa',
        approved_by_rejected_by: 'System User (05-07-2023 2:39 PM)',
        status: 'Approved',
    },
    {
        adj_no: 'SA101001006',
        date: '17-07-2023',
        type: 'Stock Adjustment',
        total_items: 1,
        total_adjusted_qty: 4000,
        created_by: 'Raj Busa',
        approved_by_rejected_by: 'System User (11-07-2023 3:53 PM)',
        status: 'Approved',
    },
    {
        adj_no: 'SA101001005',
        date: '17-07-2023',
        type: 'Stock Adjustment',
        total_items: 1,
        total_adjusted_qty: 10500,
        created_by: 'Raj Busa',
        approved_by_rejected_by: 'Narendra Chandel (14-07-2023 7:08 PM)',
        status: 'Draft',
    },
    {
        adj_no: 'SA101001004',
        date: '17-07-2023',
        type: 'Stock Adjustment',
        total_items: 1,
        total_adjusted_qty: 2000,
        created_by: 'Raj Busa',
        approved_by_rejected_by: 'Jenil Kundaliya (17-07-2023 11:26 AM)',
        status: 'Approved',
    },
    {
        adj_no: 'SA101001003',
        date: '17-07-2023',
        type: 'Stock Adjustment',
        total_items: 21,
        total_adjusted_qty: 25,
        created_by: 'Raj Busa',
        approved_by_rejected_by: 'Jenil Kundaliya (17-07-2023 11:39 AM)',
        status: 'Approved',
    },
    {
        adj_no: 'SA101001002',
        date: '17-07-2023',
        type: 'Stock Adjustment',
        total_items: 2,
        total_adjusted_qty: 30,
        created_by: 'Raj Busa',
        approved_by_rejected_by: 'Jenil Kundaliya (04-09-2023 4:39 PM)',
        status: 'Draft',
    },
    {
        adj_no: 'SA101001001',
        date: '14-07-2023',
        type: 'Stock Adjustment',
        total_items: 272,
        total_adjusted_qty: 15500,
        created_by: 'Raj Busa',
        approved_by_rejected_by: 'Jenil Kundaliya (17-07-2023 11:40 AM)',
        status: 'Approved',
    },
    {
        adj_no: 'SA101001000',
        date: '11-07-2023',
        type: 'Stock Adjustment',
        total_items: 72,
        total_adjusted_qty: 400,
        created_by: 'Raj Busa',
        approved_by_rejected_by: 'Jenil Kundaliya (04-09-2023 4:40 PM)',
        status: 'Draft',
    },
];

const stockrearrange = [
    {
        assingned_by_name:'Pujan M',
        checker_name: 'Rajdeep H',
        rack_assigned: 'D',
        lane_assigned: '7',
        total_products: '78', 
        assigned_at: '20/09/2023 06:06 PM',
        started_at: '-',
        complete_at: '-',
        no_of_queries: '-',
        found_product: '50',
        not_found_product: '-',
        new_product: '-',
        status: 'Pending',
    },
    {
        assingned_by_name:'Hiren C',
        checker_name: 'Rajdeep H',
        rack_assigned: 'A',
        lane_assigned: '2',
        total_products: '120', 
        assigned_at: '20/09/2023 06:06 PM',
        started_at: '-',
        complete_at: '31/08/2023 04:51 PM',
        no_of_queries: '-',
        found_product: '-',
        not_found_product: '-',
        new_product: '8',
        status: 'Pending',
    },
    {
        assingned_by_name:'Pujan M',
        checker_name: 'Pujan M',
        rack_assigned: 'S',
        lane_assigned: '2',
        total_products: '40', 
        assigned_at: '20/09/2023 06:06 PM',
        started_at: '-',
        complete_at: '31/08/2023 04:51 PM',
        no_of_queries: '-',
        found_product: '60',
        not_found_product: '-',
        new_product: '-',
        status: 'In Progress',
    },
    {
        assingned_by_name:'Hiren C',
        checker_name: 'Pujan M',
        rack_assigned: 'F',
        lane_assigned: '4',
        total_products: '80', 
        assigned_at: '20/09/2023 06:06 PM',
        started_at: '-',
        complete_at: '31/08/2023 04:51 PM',
        no_of_queries: '-',
        found_product: '-',
        not_found_product: '-',
        new_product: '3',
        status: 'In Progress',
    },
    {
        assingned_by_name:'Pujan M',
        checker_name: 'Pujan M',
        rack_assigned: 'H',
        lane_assigned: '2',
        total_products: '150', 
        assigned_at: '20/09/2023 06:06 PM',
        started_at: '20/09/2023 05:33 PM',
        complete_at: '31/08/2023 04:51 PM',
        no_of_queries: '-',
        found_product: '30',
        not_found_product: '-',
        new_product: '-',
        status: 'In Progress',
    },
    {
        assingned_by_name:'Hiren C',
        checker_name: 'Pujan M',
        rack_assigned: 'G',
        lane_assigned: '1',
        total_products: '90', 
        assigned_at: '20/09/2023 06:06 PM',
        started_at: '20/09/2023 05:33 PM',
        complete_at: '-',
        no_of_queries: '2',
        found_product: '-',
        not_found_product: '-',
        new_product: '6',
        status: 'In Progress',
    },
    {
        assingned_by_name:'Rajdeep H',
        checker_name: 'Rajdeep H',
        rack_assigned: 'J',
        lane_assigned: '2',
        total_products: '38', 
        assigned_at: '20/09/2023 06:06 PM',
        started_at: '20/09/2023 05:33 PM',
        complete_at: '-',
        no_of_queries: '-',
        found_product: '-',
        not_found_product: '-',
        new_product: '-',
        status: 'In Progress',
    },
    {
        assingned_by_name:'Pujan M',
        checker_name: 'Rajdeep H',
        rack_assigned: 'K',
        lane_assigned: '5',
        total_products: '70', 
        assigned_at: '20/09/2023 06:06 PM',
        started_at: '20/09/2023 05:33 PM',
        complete_at: '-',
        no_of_queries: '1',
        found_product: '10',
        not_found_product: '-',
        new_product: '-',
        status: 'Completed',
    },
    {
        assingned_by_name:'Rajdeep H',
        checker_name: 'Rajdeep H',
        rack_assigned: 'L',
        lane_assigned: '4',
        total_products: '60', 
        assigned_at: '20/09/2023 06:06 PM',
        started_at: '-',
        complete_at: '-',
        no_of_queries: '4',
        found_product: '-',
        not_found_product: '-',
        new_product: '4',
        status: 'Completed',
    },
    {
        assingned_by_name:'Pujan M',
        checker_name: 'Rajdeep H',
        rack_assigned: 'R',
        lane_assigned: '2',
        total_products: '10', 
        assigned_at: '20/09/2023 06:06 PM',
        started_at: '20/09/2023 05:33 PM',
        complete_at: '31/08/2023 04:51 PM',
        no_of_queries: '3',
        found_product: '-',
        not_found_product: '-',
        new_product: '10',
        status: 'Completed',
    },
];

const reallocation = [
    {
        file_name: 'REALLOCATION_250',
        upload_by: '(Jul 24-2023 2:56 PM)',        	
        no_of_records: '2',
        total_qty_ordered: '8',
        total_qty_fulfiled: '8',
        PN_generated_time: '24-Jul-2023 02:57:05 PM',        	
        status: '-',
    },
    {
        file_name: 'REALLOCATION_235',
        upload_by: '(Jul 24-2023 2:56 PM)',        	
        no_of_records: '-',
        total_qty_ordered: '-',
        total_qty_fulfiled: '0',
        PN_generated_time: '24-Jul-2023 02:57:05 PM',        	
        status: 'Processed',
    },
    {
        file_name: 'REALLOCATION_267',
        upload_by: '(Jul 24-2023 2:56 PM)',        	
        no_of_records: '5',
        total_qty_ordered: '7',
        total_qty_fulfiled: '9',
        PN_generated_time: '24-Jul-2023 02:57:05 PM',        	
        status: '-',
    },
    {
        file_name: 'REALLOCATION_237',
        upload_by: '(Jul 24-2023 2:56 PM)',        	
        no_of_records: '1',
        total_qty_ordered: '4',
        total_qty_fulfiled: '10',
        PN_generated_time: '24-Jul-2023 02:57:05 PM',        	
        status: 'Processed',
    },
    {
        file_name: 'REALLOCATION_298',
        upload_by: '(Jul 24-2023 2:56 PM)',        	
        no_of_records: '6',
        total_qty_ordered: '17',
        total_qty_fulfiled: '10',
        PN_generated_time: '24-Jul-2023 02:57:05 PM',        	
        status: 'Processed',
    },
    {
        file_name: 'REALLOCATION_209',
        upload_by: '(Jul 24-2023 2:56 PM)',        	
        no_of_records: '5',
        total_qty_ordered: '5',
        total_qty_fulfiled: '7',
        PN_generated_time: '24-Jul-2023 02:57:05 PM',        	
        status: 'Processed',
    },
    {
        file_name: 'REALLOCATION_247',
        upload_by: '(Jul 24-2023 2:56 PM)',        	
        no_of_records: '6',
        total_qty_ordered: '9',
        total_qty_fulfiled: '4',
        PN_generated_time: '24-Jul-2023 02:57:05 PM',        	
        status: 'Processed',
    },
    {
        file_name: 'REALLOCATION_287',
        upload_by: '(Jul 24-2023 2:56 PM)',        	
        no_of_records: '4',
        total_qty_ordered: '3',
        total_qty_fulfiled: '0',
        PN_generated_time: '24-Jul-2023 02:57:05 PM',        	
        status: 'Processed',
    },
    {
        file_name: 'REALLOCATION_212',
        upload_by: '(Jul 24-2023 2:56 PM)',        	
        no_of_records: '6',
        total_qty_ordered: '6',
        total_qty_fulfiled: '3',
        PN_generated_time: '24-Jul-2023 02:57:05 PM',        	
        status: 'Processed',
    },
    {
        file_name: 'REALLOCATION_234',
        upload_by: '(Jul 24-2023 2:56 PM)',        	
        no_of_records: '4',
        total_qty_ordered: '9',
        total_qty_fulfiled: '10',
        PN_generated_time: '24-Jul-2023 02:57:05 PM',        	
        status: 'Processed',
    },
];

const transferout = [
    {
        date: '20-09-2023',
        STN_no: 'TO101001012',
        store_code: '127',
        store_name: 'MEDKART AN JITO',
        city_name: 'ANAND',
        total_products: 1,
        total_qty: 2,
        MRP_total: '₹123.27',
        invoice_by: 'Pratibha T',
        status: 'Generated',
    },
    {
        date: '24-07-2023',
        STN_no: 'TO101001011',
        store_code: '122',
        store_name: 'MEDKART G KUD',
        city_name: 'GANDHINAGAR',
        total_products: 2,
        total_qty: 1,
        MRP_total: '₹842.35',
        invoice_by: 'System User',
        status: 'Generated',
    },
    {
        date: '19-07-2023',
        STN_no: 'TO101001010',
        store_code: '122',
        store_name: 'MEDKART G KUDAS',
        city_name: 'GANDHINAGAR',
        total_products: 1,
        total_qty: 6,
        MRP_total: '₹127.68',
        invoice_by: 'Pratibha T',
        status: 'Generated',
    },
    {
        date: '18-09-2023',
        STN_no: 'TO101001009',
        store_code: '125',
        store_name: 'J M AND K ENTERP',
        city_name: 'Ahmedabad',
        total_products: 1,
        total_qty: 3,
        MRP_total: '₹4480',
        invoice_by: 'Rajan',
        status: 'Generated',
    },
    {
        date: '17-09-2023',
        STN_no: 'TO101001008',
        store_code: '56',
        store_name: 'MEDKART B KARELIBAG',
        city_name: 'Ahmedabad',
        total_products: 2,
        total_qty: 15,
        MRP_total: '₹0.01',
        invoice_by: 'System User',
        status: 'Generated',
    },
    {
        date: '17-09-2023',
        STN_no: 'TO101001007',
        store_code: '78',
        store_name: '	MEDKART A PRERNATIRTH',
        city_name: 'VADODARA',
        total_products: 1,
        total_qty: 7,
        MRP_total: '₹441.3',
        invoice_by: 'System User',
        status: 'Generated',
    },
    {
        date: '17-09-2023',
        STN_no: 'TO101001006',
        store_code: '12',
        store_name: 'MEDKART AN JITO',
        city_name: 'VADODARA',
        total_products: 2,
        total_qty: 45,
        MRP_total: '₹93.49',
        invoice_by: 'Rajan',
        status: 'Generated',
    },
    {
        date: '16-09-2023',
        STN_no: 'TO101001005',
        store_code: '10',
        store_name: 'MEDKART AN JITO',
        city_name: 'VAPI',
        total_products: 1,
        total_qty: 9,
        MRP_total: '₹123.27',
        invoice_by: 'System User',
        status: 'Generated',
    },
    {
        date: '16-09-2023',
        STN_no: 'TO101001004',
        store_code: '6',
        store_name: 'MEDKART AN JITO',
        city_name: 'VAPI',
        total_products: 1,
        total_qty: 12,
        MRP_total: '₹123.27',
        invoice_by: 'System User',
        status: 'Generated',
    },
    {
        date: '16-09-2023',
        STN_no: 'TO101001003',
        store_code: '9',
        store_name: 'MEDKART AN JITO',
        city_name: 'ANAND',
        total_products: 2,
        total_qty: 10,
        MRP_total: '₹123.27',
        invoice_by: 'System User',
        status: 'Generated',
    },
];

const internalsales = [
    {
        date: '20-09-2023',        	
        invoice_no: 'IS101001034',
        store_code: '127',
        store_name: 'MEDKART AN JITO',
        city_name: 'ANAND',
        total_products: 1,
        total_qty: 2,
        MRP_total: '₹123.27',
        invoice_by: 'Pratibha T',
        status: 'Generated',
    },
    {
        date: '24-07-2023',
        invoice_no: 'IS101001055',
        store_code: '122',
        store_name: 'MEDKART G KUD',
        city_name: 'GANDHINAGAR',
        total_products: 2,
        total_qty: 1,
        MRP_total: '₹842.35',
        invoice_by: 'System User',
        status: 'Generated',
    },
    {
        date: '19-07-2023',
        invoice_no: 'IS101001043',
        store_code: '122',
        store_name: 'MEDKART G KUDAS',
        city_name: 'GANDHINAGAR',
        total_products: 1,
        total_qty: 6,
        MRP_total: '₹127.68',
        invoice_by: 'Pratibha T',
        status: 'Generated',
    },
    {
        date: '18-09-2023',
        invoice_no: 'IS101001076',
        store_code: '125',
        store_name: 'J M AND K ENTERP',
        city_name: 'Ahmedabad',
        total_products: 1,
        total_qty: 3,
        MRP_total: '₹4480',
        invoice_by: 'Rajan',
        status: 'Generated',
    },
    {
        date: '17-09-2023',
        invoice_no: 'IS101001045',
        store_code: '56',
        store_name: 'MEDKART B KARELIBAG',
        city_name: 'Ahmedabad',
        total_products: 2,
        total_qty: 15,
        MRP_total: '₹0.01',
        invoice_by: 'System User',
        status: 'Generated',
    },
    {
        date: '17-09-2023',
        invoice_no: 'IS101001007',
        store_code: '78',
        store_name: '	MEDKART A PRERNATIRTH',
        city_name: 'VADODARA',
        total_products: 1,
        total_qty: 7,
        MRP_total: '₹441.3',
        invoice_by: 'System User',
        status: 'Generated',
    },
    {
        date: '17-09-2023',
        invoice_no: 'IS101001098',
        store_code: '12',
        store_name: 'MEDKART AN JITO',
        city_name: 'VADODARA',
        total_products: 2,
        total_qty: 45,
        MRP_total: '₹93.49',
        invoice_by: 'Rajan',
        status: 'Generated',
    },
    {
        date: '16-09-2023',
        invoice_no: 'IS101001078',
        store_code: '10',
        store_name: 'MEDKART AN JITO',
        city_name: 'VAPI',
        total_products: 1,
        total_qty: 9,
        MRP_total: '₹123.27',
        invoice_by: 'System User',
        status: 'Generated',
    },
    {
        date: '16-09-2023',
        invoice_no: 'IS101001024',
        store_code: '6',
        store_name: 'MEDKART AN JITO',
        city_name: 'VAPI',
        total_products: 1,
        total_qty: 12,
        MRP_total: '₹123.27',
        invoice_by: 'System User',
        status: 'Generated',
    },
    {
        date: '16-09-2023',
        invoice_no: 'IS101001056',
        store_code: '9',
        store_name: 'MEDKART AN JITO',
        city_name: 'ANAND',
        total_products: 2,
        total_qty: 10,
        MRP_total: '₹123.27',
        invoice_by: 'System User',
        status: 'Generated',
    },
];

const b2csales = [
    {
        date: '20-09-2023',        	
        invoice_no: 'IS101001034',
        SO_no: '',
        sales_ref_no:'',
        pick_note: 'PS10100107',
        customer_name: 'BharatBhai',
        total_products: 1,
        total_qty: 2,
        invoice_total: '₹123.27',
        due_amount: '₹136.82',
        invoice_by: 'Pratibha T',
        payment_status: 'Partially Paid',
    },
    {
        date: '24-07-2023',
        invoice_no: 'IS101001055',
        SO_no: '',
        sales_ref_no:'',
        pick_note: 'PS10100107',
        customer_name: 'BharatBhai',
        total_products: 2,
        total_qty: 1,
        invoice_total: '₹842.35',
        due_amount: '₹136.82',
        invoice_by: 'System User',
        payment_status: 'Fully Paid',
    },
    {
        date: '19-07-2023',
        invoice_no: 'IS101001043',
        SO_no: '',
        sales_ref_no:'',
        pick_note: 'PS10100107',
        customer_name: 'BharatBhai',
        total_products: 1,
        total_qty: 6,
        invoice_total: '₹127.68',
        due_amount: '₹136.82',
        invoice_by: 'Pratibha T',
        payment_status: 'Partially Paid',
    },
    {
        date: '18-09-2023',
        invoice_no: 'IS101001076',
        SO_no: '',
        sales_ref_no:'',
        pick_note: 'PS10100107',
        customer_name: 'BharatBhai',
        total_products: 1,
        total_qty: 3,
        invoice_total: '₹4480',
        due_amount: '₹136.82',
        invoice_by: 'Rajan',
        payment_status: 'Fully Paid',
    },
    {
        date: '17-09-2023',
        invoice_no: 'IS101001045',
        SO_no: '',
        sales_ref_no:'',
        pick_note: 'PS10100107',
        customer_name: 'BharatBhai',
        total_products: 2,
        total_qty: 15,
        invoice_total: '₹0.01',
        due_amount: '₹136.82',
        invoice_by: 'System User',
        payment_status: 'UnPaid',
    },
    {
        date: '17-09-2023',
        invoice_no: 'IS101001007',
        SO_no: '',
        sales_ref_no:'',
        pick_note: 'PS10100107',
        customer_name: 'BharatBhai',
        total_products: 1,
        total_qty: 7,
        invoice_total: '₹441.3',
        due_amount: '₹136.82',
        invoice_by: 'System User',
        payment_status: 'Partially Paid',
    },
    {
        date: '17-09-2023',
        invoice_no: 'IS101001098',
        SO_no: '',
        sales_ref_no:'',
        pick_note: 'PS10100107',
        customer_name: 'BharatBhai',
        total_products: 2,
        total_qty: 45,
        invoice_total: '₹93.49',
        due_amount: '₹136.82',
        invoice_by: 'Rajan',
        payment_status: 'UnPaid',
    },
    {
        date: '16-09-2023',
        invoice_no: 'IS101001078',
        SO_no: '',
        sales_ref_no:'',
        pick_note: 'PS10100107',
        customer_name: 'BharatBhai',
        total_products: 1,
        total_qty: 9,
        invoice_total: '₹123.27',
        due_amount: '₹136.82',
        invoice_by: 'System User',
        payment_status: 'Fully Paid',
    },
    {
        date: '16-09-2023',
        invoice_no: 'IS101001024',
        SO_no: '',
        sales_ref_no:'',
        pick_note: 'PS10100107',
        customer_name: 'BharatBhai',
        total_products: 1,
        total_qty: 12,
        invoice_total: '₹123.27',
        due_amount: '₹136.82',
        invoice_by: 'System User',
        payment_status: 'UnPaid',
    },
    {
        date: '16-09-2023',
        invoice_no: 'IS101001056',
        SO_no: '',
        sales_ref_no:'',
        pick_note: 'PS10100107',
        customer_name: 'BharatBhai',
        total_products: 2,
        total_qty: 10,
        invoice_total: '₹123.27',
        due_amount: '₹136.82',
        invoice_by: 'System User',
        payment_status: 'UnPaid',
    },
];

export default {unpublished, locationmaster, minmaxmaster, moleculemaster, manufacturemaster, vendormaster, productchannelmapping,
                b2cPricingMaster, storeMaster, warehousemaster, MrpPtrData, stockadjustment, stockrearrange, reallocation, transferout,
                internalsales, b2csales };